### ISSUE TITLE
UI:Live # of resources in Library

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#100]
Please populate this number with the # of published resources in imageshare.
I assume there is a boolean flag to also check if a resource has been published or not.
Attached is where I am referring to on the index page.
![Library number of resources](https://user-images.githubusercontent.com/7736749/83769979-5e12f680-a635-11ea-814b-862415781694.png)

**Comment by sinabahram** [comment]
Just a note that no flag is needed for published VS unpublished, as that’s a WP attribute. I echo the fact that the number is supposed to be live.

**Comment by jkva** [comment]
Implemented via 9bded8229e6b429cbe1a180be074ab7a61ce7876
