### ISSUE TITLE
UI: Visually "Search" overlaps with other text on page

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#101]
The text "Search" overlaps with the text "Find and share accessible materials for your STEM classes."
This appears on the initial Index page.

![Search overlaps text](https://user-images.githubusercontent.com/7736749/83770255-b649f880-a635-11ea-935e-1c0e630da600.png)

**Comment by jkva** [comment]
For now please assume anything _off_ will be sorted out as I start cleaning up the templates once I'm finished with the functionality parts of the project (which looks like it won't be long)

**Comment by sinabahram** [comment]
Closing this because we're not ready for these kinds of issues yet.
