### ISSUE TITLE
UI: Skip to main content link always visible

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#102]
The "Skip to Main Content" is visible at the top left of the page, I would think this would be only visible to AT.
Seems to be on all pages.
![skip - visible](https://user-images.githubusercontent.com/7736749/83771708-6b30e500-a637-11ea-90ea-b1b5d795bd09.png)

**Comment by jkva** [comment]
This is a contender for removal: https://github.com/benetech/Imageshare/issues/83

**Comment by sinabahram** [comment]
No it isn’t. only the main page, as I clarified.

 

It needs to exist on other pages.

**Comment by sinabahram** [comment]
Skip to content “must” be visible. The only exception is hiding it on blur, which is a compromise we make with our super design-concerned clients, but it’s not necessary nor appropriate here. How else would a sighted keyboard user use it?

 

Happy to hop on slack or a call to discuss this.

**Comment by clapierre** [comment]
I thought there was a best practice that you backup with the keyboard which then shows the "Skip to main content" link.  That is what I have seen on other websites.  A purely visual user wouldn't need to see this, and AT would see this since it would be first on the page, and a Keyboard user could get this by the first time they press Tab or arrow then the link would show and be in focus they can then click on.

**Comment by clapierre** [comment]
@sinabahram ok so how Bookshare handles this is that you are right it is visible except you don't see the link visibly as the view is one line down on the page and when you use a keyboard to tab into that page it scrolls up to focus the link.  Can we do the same here?

**Comment by sinabahram** [comment]
Correct, that’s the compromise I’m referring to, but why hide it?

**Comment by clapierre** [comment]
It looks out of place, we don't have any other text or  menu's  up there,  It would be fine if there was a text menu up there with Skip to main content visible with the other text, but we just have the Imageshare logo and a decorative image.

**Comment by sinabahram** [comment]
What can we do to make it not look out of place?

**Comment by jkva** [comment]
I'm considering this issue still open; right now on the search results page there's a skip link that becomes visible when it gains focus.

Either way implementing them is fairly trivial at this point, so no rush.

**Comment by sinabahram** [comment]
Can we just handle this one? There is a rush in that it’s just super-simple to fix, so let’s just spend the three minutes on it to clear it off the list.

 

We just have to delete the skip link from the homepage. Problem solved.

**Comment by sinabahram** [comment]
Ignore my last comment. The other issue with homepage got handled in another issue. I'm glad we're down to just one issue on skip links now. @clapierre  if you want the skip link only visible on focus, then let's go with that. @jkva  if that is how it behaves, I'm going to close this issue.b
