### ISSUE TITLE
Unable to bulk import Imageshare JSON file

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#106]
After deleting all the resources since I updated the Subjects and needed to relink the new subjects for our 11 test resources I tried to bulk import the Imageshare-master.json file from imageshare-util directory and got the following error message

Imageshare configuration
Not enough properties at #->patternProperties[.*]:Carbon Cycle->$ref[#/definitions/resource]

**Comment by jkva** [comment]
That's `downloadable` causing problems. If you use a JSON import with `downloadable` being removed (for either Resource or Resource File), it should be fine. The field has been removed since (https://github.com/benetech/Imageshare/issues/103)

**Comment by sinabahram** [comment]
@jkva  this is not what we agreed to on the other thread at least to my and @clapierre's understanding. No downloadable for resource, but we're keeping downloadable on resource_files because we feel that is useful to know in the future. You don't have to do anything with it right now other than store it, but you could imagine this would be useful to reference in order to know a kind of badge/icon to display, maybe in order to open the link in a new tab when we know it isn't downloadable, etc. etc.

**Comment by jkva** [comment]
Yep. I'll have that sorted later today as I'm working on taxonomy management anyway.

**Comment by jkva** [comment]
@clapierre this is sorted right now. I've also added a way that you can view the generated validation schema which will make it easier to see why you're getting a validation error.

One issue I notice right now is that there are two subjects called "Inventions". They have different parent subjects (Science and History) but that doesn't help - I need a way to map the incoming subject "History" to the proper term ID via a lookup -- and for that reason the subject name needs to be unique.

**Comment by jkva** [comment]
![A screenshot of a JSON schema output showing a repeating "Inventions" subject](https://user-images.githubusercontent.com/217264/83891340-4af34a00-a74d-11ea-98d0-a08f5dc0d389.png)

**Comment by diagram-codesprint** [comment]
Right understood, I will remove the one under history.  And make sure we don't have any duplicates like this moving fwd. 
Thanks.
(Sorry was logged in for the DIAGRAM Code Sprint next week). This is Charles :)

**Comment by jkva** [comment]
@clapierre Has this been resolved?

**Comment by clapierre** [comment]
This has been resolved with updates to the JSON script (case-insensitivity), excel data itself and tweaks to the validator.
