### ISSUE TITLE
Normalise validated list of terms to lowercase

### ISSUE THREAD

**Issue by jkva** [benetech/ImageShare#108]
In coordination with the python JSON generating script generating lowercase terms on its end.

**Comment by sinabahram** [comment]
Python script changes and resulting json commited, so this is done on my end.

**Comment by jkva** [comment]
@sinabahram  can you lowercase all terms that are mapped to enums?

* license
* language
* type
* format
* accommodation

**Comment by jkva** [comment]
Lowercasing validation terms on my side via 974bdc965b05d83629323698f52ed8c96242ac62

**Comment by sinabahram** [comment]
All enums should now be lower cased in json output of python script

**Comment by jkva** [comment]
@sinabahram doesn't seem the case for licenses yet

**Comment by sinabahram** [comment]
Ahh, sorry about that. now fixed

**Comment by clapierre** [comment]
This has been fixed with Sina's last changes
