### ISSUE TITLE
Should collection search results be paginated?

### ISSUE THREAD

**Issue by jkva** [benetech/ImageShare#112]
Are we expecting collections to exist in such numbers that they should be paginated? I'm asking because I'll need to handle the logic for pagination on a per-type (resource, resource collection) basis if either of the result table pagination controls (say, moving from collection page 1 to page 2) is changed.

**Comment by jkva** [comment]
Related to #98

**Comment by sinabahram** [comment]
Yes

**Comment by jkva** [comment]
Implemented via ddf29a1a8bf7062425d5015e1b3a718079c55304
