### ISSUE TITLE
Searching "Science" does not find T-Rex which is listed under "Animal Science"

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#113]
Searching "Animal Science" finds the T-Rex model, but it doesn't find it under a "Science" search.

Science search only finds 10 Resources, of the 13 resources in our collection.  Yet all our resources should be under the "Science" main subject area.

**Comment by jkva** [comment]
I'm currently implementing paging; until then the default result size is 10, which is what you're seeing. It's currently a matter of resultset being sorted by relevance.

**Comment by clapierre** [comment]
Oh it says 20 per page which is why I am confused.

**Comment by jkva** [comment]
Sorry for the confusion. Paging is currently not implemented (#98) so that form doesn't do anything, but will be soon.

**Comment by sinabahram** [comment]
Closing for now. Not time for testing just yet.
