### ISSUE TITLE
Performing a Search should tell you how many results were found

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#114]
Currently you only see the total # of resources in our collection.
We don't really need to see this since the most important thing is how many resources were found.

Question: Should the "Skip to Main Content" be renamed to "Skip to results Found" since I assume you do not want to move the focus to the # of results found directly correct?

**Comment by jkva** [comment]
That's coming as part of Paging and Filters, you'll get a count for both relevant resources and collections.

**Comment by jkva** [comment]
> Question: Should the "Skip to Main Content" be renamed to "Skip to results Found" since I assume you do not want to move the focus to the # of results found directly correct?

That could be good. @sinabahram what do you think? Jump to results heading so as to skip the search form?

**Comment by sinabahram** [comment]
I like Skip to results, but we may tweak this as we do a deeper a11y check element by element from top to bottom.

 

Yes for now for sure, though.

**Comment by jkva** [comment]
Implemented via ddf29a1a8bf7062425d5015e1b3a718079c55304
