### ISSUE TITLE
Clean Up the Head Tag

### ISSUE THREAD

**Issue by sinabahram** [benetech/ImageShare#115]
Currently, it's a bit of a mess with multiple title daughter elements, several unused tags, an incorrect dns prefetch directive, etc. etc @jkva  please take a first pass at cleaning this up quite a bit and then we can review.

**Comment by jkva** [comment]
Yeah. Already working on this as part of general cleaning. Pushing an update later today 👍

**Comment by jkva** [comment]
Implemented via 3b3c3b8b8d616da1b3563a1450608a5a10365480
