### ISSUE TITLE
Data tables are difficult to make responsive

### ISSUE THREAD

**Issue by jkva** [benetech/ImageShare#116]
Currently the design renders resources, collections and files in data tables. These are hard to make responsive by nature. It can be done, but it's not ideal. Are we set on using tables for this, or can we use something similar like `ul` or `dl` elements? Or construct them via properly headed sections?

Just putting this out there, but as focus now moves from functionality to layout, this would be good to discuss.

**Comment by sinabahram** [comment]
Happy to explore a UL structure for this. table was only for ease of use.

**Comment by jkva** [comment]
Implemented via 3b3c3b8b8d616da1b3563a1450608a5a10365480
