### ISSUE TITLE
How to implement "back to search results" link on resource page?

### ISSUE THREAD

**Issue by jkva** [benetech/ImageShare#119]
The only way I see this work is to attach the search query variables that brought the resource up, to the resource's destination link. That way I can generate the link back to those same search results from there.

It's going to make the links a bit longer, but that's the only downside. Just wanted to raise it for consideration.

**Comment by sinabahram** [comment]
Sorry for asking a dumb question, but why not simply navigate back with the built-in JS support for history and call it a day?

 

This should be a one-liner, no?

**Comment by jkva** [comment]
I could, if we're cool with relying on JS being available.

**Comment by jkva** [comment]
So to that degree it's not a dumb question, it's rather useful to clarify the stance on progressive enhancement.

**Comment by sinabahram** [comment]
I think that if JS is not available, you have the back functionality on your browser, which we in no way are invalidating.

 

So, yes this one link may not work for you, but even there, we absolutely can make this graceful e.g. use JS to override the HREF and make the default HREF point to the previous page. Problem solved. That way, never is the link broken, but obviously, when JS is available, it’ll be nicer to move back.

 

Frankly, purely personally, I hate these links to begin with. I think the back button exists in browsers for a reason, but I acknowledge the design expectations around such controls, so I’m not at all suggesting we remove it.

**Comment by jkva** [comment]
Implemented via 98f313b682dc586df79e35665fd0a8fb5f50fa42
