### ISSUE TITLE
Resources can be bulk imported

### ISSUE THREAD

**Issue by benetechMatt** [benetech/ImageShare#12]
Imageshare administrators can import resources from .xls or .csv files.  When the file has been imported, the admin can then connect table columns with Imageshare resource fields.

- Links should be turned into clickable links within descriptions
- Ability to choose a column as the primary resource image

Duplicate resources:
The system will search for duplicate resources based on title, description and meta data.  The administrator can choose to replace, add new, or skip the resource individually and/or for all duplicates.

- Replace: the contents of the old resource is replaced with the new resource - keep the same URL due to links others may have or when stored in collections
- Skip: will keep the old duplicate and not import the new resource
- Add new: will create a new resource even though it's been flagged as a duplicate

  This will be important for importing resources from the same partner that have some updates, but also includes old data.

Once imported, resources are automatically set to "published" and available on the site

**Comment by sinabahram** [comment]
Closing because now handled in #41
