### ISSUE TITLE
"Download" attribute only works for same-domain.

### ISSUE THREAD

**Issue by jkva** [benetech/ImageShare#122]
We'd like to have resources or separate resource files download directly when their respective anchor is clicked.

However these only work via a `download` attribute, however per the MDN:

> download only works for same-origin URLs, or the `blob:` and `data:` schemes.

This means that the only way I could see this work (when we link to simple images or text files, for instance) to use a reverse proxy or another dynamic redirection rule. We also can't use the `content-disposition` header since we don't control that on the offsite aws bucket.

For the "download all files" link this isn't an issue since it seems to always be an archive which the browser won't attempt to display.

**Comment by johnhbenetech** [comment]
@jkva I believe I could set content disposition = attachment on the s3 objects. Is that a fair way to address this? I want to make sure I'm not misunderstanding

**Comment by jkva** [comment]
@johnhbenetech that would be great John 👍  can you let me know once that's done? Then I can give it a try.

**Comment by jkva** [comment]
@johnhbenetech `Content-Disposition: attachment` should do the trick 👍

**Comment by johnhbenetech** [comment]
@jkva Should be good to go. Cache/CDN stuff might take a bit to flip over, testing at my edge it seems to have propagated already.

**Comment by jkva** [comment]
@johnhbenetech Works here too. Excellent, thank you! Closing this issue.
