### ISSUE TITLE
Heading issue in search results

### ISSUE THREAD

**Issue by sinabahram** [benetech/ImageShare#127]
This is a placeholder so we can close other issues. I'm assigning to myself for now, and I will then update the assignment if something different needs to happen once we hear back from Aaron at Google or others.

**Comment by jscholes** [comment]
The level 4 headings work fine over here with Firefox/Chrome, JAWS/NVDA.  For what it's worth there's no need  for the heading to be inside the link because we're not doing block links, and I'd prefer the heading to be the parent.  But they work for me nonetheless.

**Comment by sinabahram** [comment]
@jscholes  say more, please. Why do you prefer the heading on the outside? Does that not reduce the touch target by a bit, depending on CSS? I prefer it because I feel it fixes this problem, but I wish to understand why you do?

**Comment by jkva** [comment]
Closing, @sinabahram reports it as fixed.
