### ISSUE TITLE
Two search library buttons now

### ISSUE THREAD

**Issue by sinabahram** [benetech/ImageShare#128]
When Advanced Search is activated, there are now two search library buttons. The first one should be removed of course.

**Comment by jkva** [comment]
Odd, I wonder how that happened. Vim butterfingers... thanks.
Sorted in a95d82173dd4622c8ee37847c2e2736801f68b91

**Comment by sinabahram** [comment]
Reopening this as it is broken again. The wrong button seems to have been removed.

**Comment by jkva** [comment]
Fixed in 12e08c3bb4290a78d000750be5e130ca70bcd0ff.
