### ISSUE TITLE
Type: Video is not being associated with the resource files correctly

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#129]
The master JSON file has two resource files with file accommodation of "Video" yet video is not in our dropdown list of Type's of resources available.

**Comment by sinabahram** [comment]
I'll let @jkva  comment on the data issue, but I have a higher-level question, why is "video" an accomodation in the first place? What exactly does that mean?

**Comment by clapierre** [comment]
Sorry meant to say file Type, not accommodation, I thought I fixed that.  I was wondering / editing the ticket if we should automatically add new file types and accommodations based on the JSON file, but then we wouldn't have the ability to validate the data.  So I was removing that part.

**Comment by jkva** [comment]
Those validations are determined through types/accommodations/formats/licenses etc which are defined in the admin interface, thus you can add these dynamically.

I'm currently out with the fire department, we're having extreme flooding today, but I can check back later 👍

--
Job van Achterberg | 3ode
Middeldiepstraat 51 | 3361VR Sliedrecht | http://www.3ode.nl
M: 06 46 77 80 60 | E: mail@3ode.nl | KvK: 63716348

**Comment by jkva** [comment]
Ah, I misunderstood the issue. This is about files having types assigned.

Are those files published?

--
Job van Achterberg | 3ode
Middeldiepstraat 51 | 3361VR Sliedrecht | http://www.3ode.nl
M: 06 46 77 80 60 | E: mail@3ode.nl | KvK: 63716348

**Comment by clapierre** [comment]
Yes they are live and shown in the results
IE:
http://imgsdev.wpengine.com/btis_resource/waves/

Which has "Video" as its Type, yet under the Advance Search options "Video" is not one of our choices.

Also why is there 5 rows for this Resource with all the same information in the link provided above?

**Comment by jkva** [comment]
The files have status "draft". They're shown, but they don't register for a given term. I've made a specific issue in https://github.com/benetech/Imageshare/issues/130.

**Comment by jkva** [comment]
The underlying issue is that whatever is imported is `draft`, but when a resource gets published, its underlying resource files don't. So I'll address that.

**Comment by jkva** [comment]
This was addressed via issue #130 and implemented via aaa1430dc99ff3737b352c1770f7e09884d09284
