### ISSUE TITLE
New Timber Plugin Update available

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#132]
here is a new version of Timber available. View version 1.16.0 details or update now.

Warning: This new version of Timber introduces some major new features which might have unknown effects on your site.
Is your theme in active development? That is, is someone actively in PHP files writing new code? If you answered "no", then DO NOT UPGRADE. We're so serious about it, we've even disabled the update link. If you really really think you should upgrade you can still download from WordPress.org, but that's on you!

**Comment by sinabahram** [comment]
@jkva  are we good to go on this update? If so, let's make that happen then transfer all plugin-related issues/tasks to @johnhbenetech  for future management.f

**Comment by jkva** [comment]
I'll check locally tomorrow 👍

**Comment by jkva** [comment]
Looks good. @johnhbenetech when you deactivate the plugin you'll get the update option after which you can reactivate; you don't necessarily need to download the plugin and install by hand.

**Comment by johnhbenetech** [comment]
Done (dev and staging)
