### ISSUE TITLE
There is a new version of Advanced Custom Fields available

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#133]
Customize WordPress with powerful, professional and intuitive fields.Version 5.8.11 \| By Elliot Condon \| View details
--
There is a new version of Advanced Custom Fields available. View version 5.8.12 details or update now.

**Comment by sinabahram** [comment]
@johnhbenetech  I'm assigning this to you as plugin management will presumably be in your camp.

**Comment by johnhbenetech** [comment]
Done
