### ISSUE TITLE
Auditive instead of Auditory

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#135]
So where did “Auditive” come from?  I would have expected “Auditory”, but changing this from Auditive to Auditory in the Wordpress Accessibility Accommodations section changes it on the website but found 0 entries, even after reimporting. 

Also this is not in our master json file so curious how this works, and how do I change it?

**Comment by sinabahram** [comment]
that was just sample values used before importing was working, and it's why you can control any/all of them from within WP dashboard.

**Comment by jkva** [comment]
I reopened it because it does pose an issue; when modifying categorisation terms for resources and resource files, the search index for those resource and files needs to be regenerated so you can search for "Auditory" and it still works. Implemented via 6111c1e05e005e10bf66628b9f218531de74b473.
