### ISSUE TITLE
No way to go to external Resources

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#138]
For example the Dog Café there is no way to go to the DCMP video to watch it.

For external resources there should be a button
I still need to figure out the best name maybe

"Visit: resource_source" ie: "Visit: DCMP"
Will you be able to tell if this is an external file by the URI or do we need a true/false flag for external resources?

(Note this may change I need to speak to folks internally for the exact text in the button.)

**Comment by jkva** [comment]
Looking at the file it's set to not be downloadable, so I could logically infer that if a file has a resource url set, but downloadable is false, that it's an external visitable resource.

I'd probably make the heading clickable in that case, or have a `visit` button instead of `download`.

**Comment by sinabahram** [comment]
I agree with @jkva  about how to determine. Then, instead of download, can we simply say "Visit" and call it a day?

**Comment by jkva** [comment]
@clapierre have a look at the dog cafe page, see how you like that.

**Comment by clapierre** [comment]
@jkva Looks great!
