### ISSUE TITLE
Aspect Ratio not kept in File view for Featured Image

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#139]
See the screen shots. 

Alt: In the search results the image looks correct
![Screen Shot 2020-06-19 at 9 39 28 AM](https://user-images.githubusercontent.com/7736749/85158032-1ed9cd80-b211-11ea-9ed7-f52bce5d180b.png)

Alt: In the File resources the image is distorted.
![Screen Shot 2020-06-19 at 9 39 43 AM](https://user-images.githubusercontent.com/7736749/85157995-1386a200-b211-11ea-9a4b-7ef0aed1b912.png)

**Comment by jkva** [comment]
Addressed via 3603b5c2488e37a06071e217fea8dfcfb9fed6f0

**Comment by clapierre** [comment]
This still seems to be an issue for this Resource, the aspect ratio is skewed in the File Resources Page.  Looked fine in the Search results page.

Alt: closeup of Frog 2D image which is stretched horizontally.

![Screen Shot 2020-06-22 at 8 31 38 AM](https://user-images.githubusercontent.com/7736749/85306141-e8938c80-b462-11ea-8f03-da6566e0e20b.png)

**Comment by jkva** [comment]
Addressed in c2546dc0907d1b483f09f0138a69ed72946eea8e
