### ISSUE TITLE
Copyright policy posted

### ISSUE THREAD

**Issue by benetechMatt** [benetech/ImageShare#14]
Current terms of service should be enough
https://imageshare.benetech.org/terms-of-service/

**Comment by sinabahram** [comment]
Has this been created as a page in the WP instance? If not, @johnhbenetech  or @clapierre  can you please do so? We obviously can't link to the old version of Imageshare for this content as it will not exist anymore. @jkva  can you please confirm the link in the bottom then goes to this new page once it exists? Then can we please close this issue once those two things are done?

**Comment by clapierre** [comment]
So this was the [page to the Privacy Policy](https://imageshare.benetech.org/privacy-policy/) old Imageshare page.  As for Copyright we just had at the bottom of all pages
© Copyright 2020 Benetech. All Rights Reserved.
@johnhbenetech Do you think this will suffice and we just copy this page and duplicate it on the new site?

**Comment by johnhbenetech** [comment]
@clapierre @sinabahram I'll post my slack question here:

"quick question. I was creating the TOS page, and by default permalinks are id based (example: ?postid=32). Should i change them to be slug based (example: /terms-of-service). i know ID based ensures uniqueness, but I can see lots of benefits to the slug based including a more readable URL. I just dont want to mess up URL scheme on your side for resources"

Addiitonally, I don't know what im talking about ultimately, but the content doesn't look to be structured accessibly. I don't see headers, it's all paragraphs. So someone will have to restructure appropriately

**Comment by clapierre** [comment]
I am cleaning up the Headers for the TOS page now

**Comment by sinabahram** [comment]
Yes to slug-based, but let’s do that after getting @jkva to confirm he doesn’t care.

**Comment by johnhbenetech** [comment]
Ok @sinabahram @jkva I've made the pages for the various footer links. I don't think we will have the contribute page, but @clapierre can tell me i'm wrong:

Contact Us: http://imgsdev.wpengine.com/contact-us/
Terms of Service: http://imgsdev.wpengine.com/terms-of-service/
Privacy Policy: http://imgsdev.wpengine.com/privacy-policy/
About Imageshare: https://imgsdev.wpengine.com/about-imageshare/

**Comment by sinabahram** [comment]
Sounds great. I'm closing this issue then.
