### ISSUE TITLE
Collections Aspect ratio of image changes between Featured Collection, Search Results Page & Resource Files Page

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#140]
Alt: Original in Word Press

![Screen Shot 2020-06-19 at 9 50 26 AM](https://user-images.githubusercontent.com/7736749/85159414-55641800-b212-11ea-938b-39bfbca084f9.png)

--------

Alt: Search results page shows Collections image with square aspect ratio (different from original) 

![Screen Shot 2020-06-19 at 9 46 07 AM](https://user-images.githubusercontent.com/7736749/85158999-c3f4a600-b211-11ea-8d43-4454d02e8201.png)

--------

Alt: Resource page that is part of a collect, image looks distorted.

![Screen Shot 2020-06-19 at 9 46 21 AM](https://user-images.githubusercontent.com/7736749/85159225-0fa74f80-b212-11ea-842b-84f16abec7d5.png)

--------
Alt: Featured Collection on index page

![Screen Shot 2020-06-19 at 9 51 23 AM](https://user-images.githubusercontent.com/7736749/85159518-775d9a80-b212-11ea-8aec-061a148934a0.png)

**Comment by jkva** [comment]
The image is clipped because it becomes a thumbnail; WordPress automatically clips a rectangle, which is why the image looks a bit different.

Aspect ratio on shrinking viewports is addressed via 4ca4f89e0cde19818aeb2f9d32467998a16185ed
