### ISSUE TITLE
Images missing for resource files

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#141]
We should have a thumbnail view for each image.
For non image file types I will have our marketing folks create thumbnail images to represent the various file types.

IE: Txt, Audio, Text, PDF, Word, Tactile, etc.

Ideally this could be done outside of the JSON file based on file type.

This is what I am thinking of:
Alt: thumbnail image of resource file on left side of File name, download, description and details.

![Screen Shot 2020-06-19 at 10 11 27 AM](https://user-images.githubusercontent.com/7736749/85161975-6a8e7600-b215-11ea-9e1a-8f20c1c519f7.png)

**Comment by clapierre** [comment]
What should the file format be for these Icon's?  PNG or SVG?
I assume if we can get it SVG but will PNG work as well?
Also what should be the resolution ideally be?

**Comment by jkva** [comment]
PNG or SVG depends on the complexity of the images and the need for scalability. PNG should be fine given they're icons. They'll be displayed small anyway and they can be cached easily.

**Comment by clapierre** [comment]
@jkva I have the new icons from Marketing, I think they look great.
Here are 2 different sizes they gave me, let me know which ones you want and I will upload all the rest.

alt: small icon for PDF
![PDF-72](https://user-images.githubusercontent.com/7736749/85464300-54a5eb80-b55c-11ea-9568-3b630db560af.png)

alt: large icon for PDF
![PDF](https://user-images.githubusercontent.com/7736749/85464384-6a1b1580-b55c-11ea-80e1-77e9cf5ac310.png)

**Comment by jkva** [comment]
@clapierre these small ones seem the right size. Fancy!

**Comment by jkva** [comment]
Implemented via e846bba5a1775ca0891c56ddafdffa0e8cc6b412

@clapierre keep in mind that for this to work, each defined type that has a published resource needs to have its thumbnail defined or this won't render correctly.
