### ISSUE TITLE
How to add a Resource that is only a Video from DCMP library?

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#143]
It seems I need to select a File (which is required.)
But I don't have a file, only a Link to where you can download the Resource File.

This is done in WordPress "Add Resource"
Alt: wordpress screen shot showing the required Files.

![Screen Shot 2020-06-19 at 12 09 19 PM](https://user-images.githubusercontent.com/7736749/85172347-b9440c00-b225-11ea-9aca-4d105f8f9ab5.png)

**Comment by jkva** [comment]
Isn't this a valid entry to create as resource file and link as usual? Alternatively we'd have to extend the data model to account for this case.

**Comment by sinabahram** [comment]
@jkva  valid maybe, but not practical or probably ever done. All resource files are stored in s3 or some other remote URI, so an edit field to paste the S3 URI is what's needed here to facilitate manual creation; otherwise, how can someone use the dashboard to make a resource file hosted on S3?

**Comment by sinabahram** [comment]
@clapierre  I think there's some confusion on the steps you are taking, because this already works over here.

1: Go make a resource file and set its uri field to the DCMP address
2: make a resource, and then add that single resource file to it.

There's no file upload/browse dialog anywhere. You're done

**Comment by jkva** [comment]
* Resource Files -> add new
* Set the URI field to your S3 link
* Fill in rest of fields
* Publish

* Resource -> add new
* In "Files" field, select the file you created
* Fill in rest of fields
* Publish

That should be all you need.

**Comment by clapierre** [comment]
Ok that makes sense, thanks for the Steps @jkva (I assume there can't be a button to : Publish and Create Resource" which would take you to the "New Resource" page?
Thanks

**Comment by jkva** [comment]
@clapierre for my clarification, where would you expect this button to be?

**Comment by diagram-codesprint** [comment]
ideally it would be on the "Add Resource Files" page in Wordpress

See attached image: "Publish & add new Resource"
 
![Screen Shot 2020-06-22 at 11 12 05 AM](https://user-images.githubusercontent.com/39660227/85321632-d3762800-b479-11ea-92ab-a7d253c8aec4.png)

**Comment by clapierre** [comment]
Sorry commented while being in my other GitHub account.

**Comment by jkva** [comment]
And then you'd want to be taken to the "Add new Resource" page with the file you just created already associated so you'd just have to fill in the extra details and be done with it?

**Comment by clapierre** [comment]
Yeah if we could do that it would make it very easy to add new resources.  If this is a lot of work then we can skip this as this is a nice to have feature.

**Comment by sinabahram** [comment]
I discussed with @jkva  and this would be a good amount of work, so I'm going to say no, sadly, on this one, @clapierre. Glad we got the underlying topic on this issue figured out, though, so I'm also closing this one out.
