### ISSUE TITLE
WordPress: Adding Resource Unclear what resource files are being added

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#149]
A lot of resources have the same name "eyeball" but one is for an STL, JPG etc.
any way we can added the file type here to make them unique?
![Screen Shot 2020-06-19 at 1 30 00 PM](https://user-images.githubusercontent.com/7736749/85177516-2315e300-b231-11ea-9bcb-2ae6463e08c6.png)

**Comment by jkva** [comment]
Implemented via d8df1f690c393a66bb111df58867fc6f401b03d3
