### ISSUE TITLE
Can we remove those templates we don't need?

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#154]
There are 4 updates to the following Templates which I would rather nuke if we don't need them.
Twenty NineteenYou have version 1.4 installed. Update to 1.6.
Twenty Seventeen | Twenty SeventeenYou have version 2.2 installed. Update to 2.3.
Twenty Sixteen | Twenty SixteenYou have version 2.0 installed. Update to 2.1.
Twenty Twenty | Twenty TwentyYou have version 1.1 installed. Update to 1.4.

**Comment by jkva** [comment]
@clapierre yep, these can all go as far as I'm concerned. They're just default install artefacts. @johnhbenetech I don't think they're part of the repo, I believe they're part of the ignorefile, so presumably they can be deleted via the admin interface.

**Comment by johnhbenetech** [comment]
yeah, they were just part of the core install. i've removed from dev and staging.
