### ISSUE TITLE
Alphabetize Accessibility accommodations 

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#155]
The advance search for Accessibility accommodations seems to be in a random order

Alt: dropdown not in alphabetical order
![Screen Shot 2020-06-23 at 6 16 59 AM](https://user-images.githubusercontent.com/7736749/85409414-a037a580-b51a-11ea-8e8d-2df352223448.png)

Should have Audio, and then all the sub-accommodations for Audio, then Text and its sub accommodations and finally Visual and its sub-accommodations.

**Comment by jkva** [comment]
Implemented via 6d82bbe8e09a7abcd6152b84e8a6a3436af31b54
