### ISSUE TITLE
When I reimported I am getting duplicate entries

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#157]
Not sure why this happened.
The resources were all in draft state if that matters.

Alt: Collection add resources showing duplicate entries

![Screen Shot 2020-06-23 at 12 52 58 PM](https://user-images.githubusercontent.com/7736749/85453419-af394a80-b550-11ea-8c49-6bdf9487b47d.png)

**Comment by sinabahram** [comment]
Thought this never had a chance to finish, so aren’t all bets off? Need to delete and start over, right?

**Comment by jkva** [comment]
Only published posts are updated through consequent imports. Since all existing posts were drafts, they are duplicated.

**Comment by clapierre** [comment]
Oh, so that is an issue if we hadn't published something and then re-import it we now get two resources with what might be different or the same data.

Can this work the same for any resource status?

**Comment by jkva** [comment]
> Can this work the same for any resource status?

Can you clarify the question? Do you want things to always update based on a given unique constraint such as the title and subject?

**Comment by clapierre** [comment]
Correct, doesn't make sense to get a duplicate entry if the resource is in draft mode.

**Comment by jkva** [comment]
Now updating when either draft or publish. c4b04223f3dd4d5f0ebdfe21d03c233e4bc65d78
