### ISSUE TITLE
Resource File: "Author" is missing

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#159]
We need an "Author" field added to our data model, for file's. Not all files within a resource are authored by the "Source", and in order to include them in that resource we must acknowledge the author who created them.

I realize there is a ripple effect and I tried very hard not to have any for this project but it was brought to my attention when we are getting additional resources to add to Imageshare that 3rd parties are enhancing the collections of our partners resources including additional alt text descriptions, extended descriptions etc.

Needed is to add a "file_author" to the JSON import, (I just tested this with Imageshare-Master.txt and the new Imageshare-Master.json has the new file field "author".

Add "Author" to WordPress: Resource File view, and the ability to add "Author" when "Add New Resource File"
Finally, if author field is present: Add "Author" to the list of File Resource flex grid view after License.

Again apologies for not catching this sooner, but this will be a blocker for acquiring content if we can't acknowledge the author for those files they have contributed.

**Comment by jkva** [comment]
Implemented via 1a15918c88045cfb23e58b7c6aa7ebbd55fafc30
