### ISSUE TITLE
Importing Behavior Existing vs. New and their status

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#169]
Current behavior when importing is:
New resources are marked as Status = Draft

Existing resources 
Draft: resource stays as draft
Published: resource stays as published
Pending review: resource gets re added as a new draft resource (now we have both a pending review and draft resource)

This is how import should work based on resource status:

New resources -> status=“draft” (Current behavior: OK)
Existing “published” resources -> status=“pending review” (changes to ‘pending review’) (**NEW)
Existing “pending review” resources -> status=“pending review” (ie. stays as ‘pending review’)  (**NEW)
Existing “draft” resources -> status=“draft”  (ie. Stays as draft) (Current Behavior: OK)

So therefore we keep new resources the same and mark their status as draft as we do currently.

However existing resources that are re-imported are either marked "pending review" if their status was "published" or was "pending review" but if their status was "draft" we keep their status as draft on re-import.

**Comment by jkva** [comment]
Implemented via 13cd82d
