### ISSUE TITLE
Reading level in description editor

### ISSUE THREAD

**Issue by benetechMatt** [benetech/ImageShare#17]
add a reading level tool that tells people what level their text descriptions are for when they write it.  Ensure that the descriptions are appropriate for the audience

**Comment by benetechMatt** [comment]
I was thinking it shows the reading level as they type and if maybe if it’s above the selected reading level then it has a ! at next to the reading level.  unobtrusive but informative.
The next level would be annotating words/phrases that are above the intended audience within the text area and offering alternatives

**Comment by clapierre** [comment]
Closing all non-MVP issues
