### ISSUE TITLE
Number of files looks like a button

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#173]
The number of files a resource has looks very similar to a button.

Can we highlight the number found without making it look like a button?  (Now I know the buttons also includes and underline but the shape and color and rounded edges makes it too much like a clickable button.

alt: image showing the "39" files looking similar in color and background shading as the "Download" or "Download all files (39) button

![Screen Shot 2020-07-07 at 12 24 17 PM](https://user-images.githubusercontent.com/7736749/86832549-2ab8f280-c04d-11ea-9b17-bfcefb83a069.png)

**Comment by clapierre** [comment]
I like the style of it but due to the background color and rounded corners it just looks like something you would click on.

Maybe just plain Text?

Files: 39

Or maybe just a different background color say light gray? (although we need to make sure of color contrast.

**Comment by sinabahram** [comment]
+1 to plain text

**Comment by jkva** [comment]
Implemented via 8451f95
