### ISSUE TITLE
Unable to bulk import

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#174]
Until #171 has been addressed bulk importing using JSON is broken.
This is now a blocker for me to add data this way into Imageshare.

**Comment by sinabahram** [comment]
@clapierre  thanks for bringing this up. Since it doesn't map to a technical requirement e.g. we have the underlying ticket. I'm closing it, but not ignoring it at all. Hoping to have this unblocked for you by tomorrow.
