### ISSUE TITLE
Search results should give preference to resources with multiple files

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#175]
Currently if you search for "frog" you get you get first 2 videos about a frog before you get  to the third resource found "Frog Dissection 2D" which contains 39 files about frogs (images, simplified, extended descriptions, images) etc.

I would expect this resource to show up first in the list of resources found in our database.

Alt: screenshot of search results showing frog searched and the resource with 39 files comes us 3rd in the list.
![Screen Shot 2020-07-09 at 9 34 22 AM](https://user-images.githubusercontent.com/7736749/87066434-6bd51200-c1c7-11ea-8b46-ece29c8b2559.png)

**Comment by sinabahram** [comment]
Charles, what is the specific criteria here? for example, I find those search results reasonable. They’re all about frog. Are you asking that resources with more files get sorted to the top? Therefore, sort search results by the resource’s file count?

**Comment by clapierre** [comment]
Yes I think that will work fine @sinabahram having those resources with the most files associated with them move to the top would be ideal.  This way when we have 40 videos on frogs, and one resource with multiple tactile, images, 3d models that this one will be placed at the very top.

**Comment by jkva** [comment]
I don't know how feasible this is. Order is by full-text search relevance, and WordPress doesn't allow for custom sorting at that point.

What I could do is manually sort the posts the full text search retrieves and sort them by file count, so then it's relevance followed by file count, but keep in mind that this then gets done for each paged set of results. Which might not matter all that much, but it needs to be mentioned.

**Comment by clapierre** [comment]
Shouldn't then if a Resource has multiple files all of which have "frog" in the name of the file be by default a higher priority.  

If we have to do the sorting afterwards based on # of files thats at least something but realize its not ideal if we get a lot of resources on multiple pages like you said, a workaround for the user is to increase that to show 100 per page so that will then reduce the likelyhood that on page 2 with the 101'th resource having 50 files doesn't show up on the first page, but is better than nothing I guess.

**Comment by jkva** [comment]
I'll see if I can tweak the weights, but I suspect the terms get normalised. Will check over the coming days.

**Comment by clapierre** [comment]
@jkva what if we give preference to Accessibility Accommodations.
(ranked in order, which we can tweak as needed)

Extended Description
Text Description
Simplified Description
2D Tactile Graphic
3D Model
Audio
Video

Thoughts?

**Comment by clapierre** [comment]
I think I would still like to see those resources with multiple files be ranked higher 
IE: 
Resource 1
2 files (Image + extended Description)
Resource 2
10 files (Images + extended Descriptions)
Ideally Resource 2 would get ranked higher since it has more extended descriptions than Resource 1

**Comment by sinabahram** [comment]
@jkva  what exactly do you have control over on search? is count of files available as a weight? What about just weighting files higher so that if multiple filenames mention a search term, the resource subsequently gets ranked higher? Basically, what levers exist for us to easily tweak here?

**Comment by jkva** [comment]
I've been working on this just now. I've added an extra search cluster consisting of a resource's file contents, but it doesn't seem to make much of a difference so far.

**Comment by sinabahram** [comment]
I suspected that may be true. Is it possible at all to involve counts as a post-search sort on an underlying dataset returned from search? In other words, can we manipulate post-search but pre-pagination?

 

If so, then we can simply implement a rule per Charles’ post, but have it execute post-search, which could address this issue completely.

**Comment by jkva** [comment]
>  In other words, can we manipulate post-search but pre-pagination?

Yes, but that will only ever be on a paginated resultset, which may cause unexpected results when moving through pages.
Honestly, this is a full-text search engine and it is not able to see significance in arbitrary file counts. I'll see if I can come up with another solution using relevance weights.

**Comment by jkva** [comment]
I think this one must be closed. Adding containing files content to the search cluster doesn't seem to make a difference, neither does tweaking the weights. I can hook in the SQL query that gets generated and potentially add a clause for file counts; however the search results are ordered by keyword relevance, not file count. I don't see the point of ordering by [relevance, file_count] because you'd mostly get the same response. You could order by [file_count, relevance] but that can really mess with your results if a less relevant resource happens to have more files.

**Comment by clapierre** [comment]
Understood.  We will leave this for now and see how folks use this and if there are any other complaints about not finding the relevant resources.
