### ISSUE TITLE
Collections "Curated by" not "Contributed by" 

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#176]
A collection may not be contributed by the author, but only picked by them.

Change the word "contributed" to "curated" on the Collections results pages.

Alt: Search results page showing where the word needs to be replaced.

![Screen Shot 2020-07-10 at 6 23 38 AM](https://user-images.githubusercontent.com/7736749/87159589-6f73a200-c276-11ea-9630-1406c43a6cb1.png)

**Comment by jkva** [comment]
Implemented via 9aeb50a
