### ISSUE TITLE
Accessibility Statement Page

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#178]
@theladymay We need to have the content for our Accessibility Page.  Lets look at PAC's https://pac.bz/accessibility/ page and come up with something for Imageshare.  We also need to add that the Video featured images that are still images from the DCMP video library are not accurately described but this work is in process and should be done by January of 2021.

Once we have the text for this page, this will be added to our footer
About Imageshare
Contact Contribute **Accessibility** Terms of Service Agreement Privacy Policy Resources

**Comment by clapierre** [comment]
First pass at our Accessibility page.  @theladymay and @sinabahram let me know what you think.

**Comment by jscholes** [comment]
@clapierre The words "contact" and "us" are marked up as separate links:

* contact -> https://imageshare.benetech.org/contact-us
* us -> https://pac.bz/contact

I'm pretty sure this was unintentional, so "contact us" can just be marked up as a single link.  Note that its text should indicate that it will open a new tab.

> addition, there are subtle affordances such as slides reading out automatically when the next or previous buttons are activated.

Are there any carousels on the site?

> We may link out to 3rd party multimedia content and do our best to vet these videos are captioned and ideally also have audio descriptions as is the case with our DCMP videos you may visit.

This sentence is confusing, partly because it isn't grammatically correct and partly because there are no commas and such to separate the various clauses.

> All buttons or links have textual labels so that the accessible name of a component is always visible.

I don't think this is entirely true for Imageshare.  For example on the search results page, the "Update Resources" and "Update collections" buttons only have the word "Update" in their visible labels.

**Comment by clapierre** [comment]
Nice catch, sorry about that yeah my bad.  All fixed.

**Comment by clapierre** [comment]
Whoops there is more to fix.

**Comment by clapierre** [comment]
@jscholes how should I go about indicating this will open in a different browser window?  Or should I just have these open in the current window?

**Comment by clapierre** [comment]
@jscholes I don't know what you are referring to?

All buttons or links have textual labels so that the accessible name of a component is always visible.
> I don't think this is entirely true for Imageshare. 
> For example on the search results page, the "Update Resources" and "Update collections" buttons only have the word "Update" in their visible labels.

Can you provide a screen shot?  And is this something we should address?

Also I am wondering @jkva, if the links for Pagination of Resources and Collections will all have the same link name for (First Page, Previous Page, Next Page and Last Page) and if that will be an accessibility issue for both Screen Readers and Voice dictation users.

**Comment by sinabahram** [comment]
They do have a visible textual label, just not a comprehensive one,  @jscholes  but I agree with the rest of your comments and I also opened #237  as a result.

**Comment by sinabahram** [comment]
don't open a new tab.

**Comment by jscholes** [comment]
> They do have a visible textual label, just not a comprehensive one

Agree with that.  I should've quoted more specifically, to highlight:

> the accessible name of a component is always visible.

**Comment by sinabahram** [comment]
ahh, yup, I agree that's inaccurate as written, but hence my comments about this being a copy/paste instead of rewrite specific to Imageshare in #237 .

**Comment by clapierre** [comment]
@sinabahram Ok, we no longer open in a new tab.

**Comment by clapierre** [comment]
@jscholes / @sinabahram  with the improvements made to the accessibility page, are we good to close this?

**Comment by sinabahram** [comment]
Yes, but please see my comment on the other related issue for this page, #179.
