### ISSUE TITLE
Link to actual Pages in Wordpress

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#179]
All the links in the footer should link to our actual pages in Wordpress

About Imageshare 
Contact
Contribute
Accessibility (newly added to footer)
Terms of Service
Privacy Policy
Resources
FAQ (newly added to footer)

**Comment by jkva** [comment]
Implemented via 3d82238fda9830b4186d432cb7e1735eed58f8bf

**Comment by jkva** [comment]
@clapierre this menu can be modified to your liking in the admin; the `Footer` menu.
