### ISSUE TITLE
Deliver search results from other repositories

### ISSUE THREAD

**Issue by benetechMatt** [benetech/ImageShare#18]
search open licensed repositories that aren’t accessible and allow users to select them and add a text description right away and then add it to ImageShare.  
Could work for YouTube + descriptive audio and or captioning tool
Goal: reduce barrier to adding content. Offer actionable solution when a resource doesn’t exist in ImageShare.
Creative Commons image search would be the first place to include

**Comment by clapierre** [comment]
Closing all non-MVP issues
