### ISSUE TITLE
Advance Search - Add "Source" option

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#180]
We need a way to search by Source. 
Currently we have
Subject, Type, Accessibility
please add Source after Accessibility.

IE: 
Subject, Type, Accessibility, Source

**Comment by jkva** [comment]
@clapierre do you expect this to be a dropdown with distinct sources?

**Comment by clapierre** [comment]
Yes

**Comment by jkva** [comment]
@clapierre do you expect this to become a filter (where you can filter with multiple sources) or a one-time only dropdown selection?

**Comment by clapierre** [comment]
If we can do multiple sources that would be great but then that would be the only filter which behaves like an OR with every other filter being an AND. So for consistency we should really only allow one and if the pick two it would always find 0 results since a resource can only every have one source. Not sure if we can prevent that.

**Comment by jkva** [comment]
I've added now without a filter, let me know how that works for you. I would agree that it makes little sense to filter by multiple sources - so for now I've added a simple selection dropdown with a list of used sources.

**Comment by jkva** [comment]
Implemented via 61e00c0246b11b885e40c1bc3107c4d400cd0602
