### ISSUE TITLE
Advance Search Responsiveness

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#181]
Once we add the new term to the advance search criteria (#180) the responsiveness of this section should be similar to how we do "Collections" and as you shrink the screen width the collections move from 4 across, to 2 across and finally a single list for small screen sizes.

If we can do the same for Advance Search as a CSS Flexgrid such that for large screen sizes we have

Subject, Type, Accessibility, Source [Search Library]

Medium sized screens would have

Subject, Type
Accessibility, Source
 [Search Library]

And finally Cellphone sized screens would be a vertical list
Subject
Type
Accessibility
Source
[Search Library]

**Comment by clapierre** [comment]
I believe this may be related to the new bug I found today #222.  Hopefully fixing this as a flex-grid responsive design will address the issue found when zoomed in on a Mac for low vision users.

**Comment by jkva** [comment]
Implemented via 08351f498a5a043502a95e758ced0994a206dc1d
