### ISSUE TITLE
Search Posts in Wordpress won't find draft/pending posts

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#183]
When you use text search to find a specific post it seems to be only searching the published posts.
Even when I am on All posts then search for "Lakes in an Ocean" which is in Pending, I don't find that post.

**Comment by jkva** [comment]
![Screenshot of Lakes in an Ocean being found in status Pending](https://user-images.githubusercontent.com/217264/87816161-29ff3800-c867-11ea-9c27-a350568923ae.png)
~~I'm unable to reproduce this.~~ Hmm, I can. Weird, will see what's up.

**Comment by jkva** [comment]
Implemented via 6232c9ddd1df0a666dceffa29fe5112df280862e
