### ISSUE TITLE
Re-Import Resource produces files which are pending

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#184]
When you have a resource that was published.  Then you re-import that resource, it changes status to draft as well as its files. (this is fine)

When you change the status from draft to published, the resource becomes published but all associated files still are "pending" and the Published date doesn't change either.

Alt: Re-published on July 15th shows original published date yesterday, and its associated files which were published yesterday are now "pending" as shown in the Files column.

![Screen Shot 2020-07-15 at 7 48 12 AM](https://user-images.githubusercontent.com/7736749/87559871-adeecf80-c66f-11ea-977b-a06dbb7378f5.png)

**Comment by clapierre** [comment]
It seems that when your mark a pending resource with pending files as a resource that has been published the resulting files do not get published as well.

It seems that if I mark both the resource and its associated files as "draft" then publish the resource from draft (with its now associated "draft" files) then both the resource and its associated files all get the status of "published" which resolves issue #187 

This behavior should be the same regardless of the status of the resource's files.  if we publish a resource all associated files regardless of status should be published and the associated linkage for Type/file accommodations etc. with those files should be associated with this resource.  Because it seems publishing all resources then publishing the associated files does not make this linkage.

**Comment by jkva** [comment]
Resolved via d3c7c23
