### ISSUE TITLE
Choose featured image

### ISSUE THREAD

**Issue by benetechMatt** [benetech/ImageShare#19]
any image added to the resource can be selected as the "featured image" for the resource.  The featured image is displayed at the top of the resource by the title.
The featured image is always from the first item in the resource_ResourceFileIDs.
if the first item in the ResourceFileIDs does not have a resourceFile_rPreviewImage then a default image for this file resource type
Resource Types will be: Image, 2D Tactile, 3D Model, Audio, Video, Lesson Plan, Manipulative, Text Document, Handmade Object) 

TODO: add default images for Types

**Comment by clapierre** [comment]
This will be rewritten in new issues.
