### ISSUE TITLE
Placement of "Clear search parameters" button

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#190]
The placement and look of the "Clear search parameters" button is not ideal.  The button hasn't been styled to match the other buttons in Imageshare (dark blue / rounded corners) and the placement is too far from the search field and current filters to be noticed by initial testers.

alt: screenshot showing where the button "clear search parameters" should look like and move to. (Between "Try searching geology..." and "Current Filters"
 
![Screen Shot 2020-07-15 at 4 12 10 PM](https://user-images.githubusercontent.com/7736749/87609161-a3a3f400-c6b6-11ea-856a-3a50adb734bc.png)

Note: image button color/size is just an approximation

**Comment by sinabahram** [comment]
Good chat with @clapierre. Here's what we've got for this issue:

1. Rename htis button to "Clear Search"
2. Style this button just like the other buttons on the site
3. Move this button after the heading that says "Search Collections or Resources"

**Comment by jkva** [comment]
Implemented via 9f7142975189113db676afb304c292afd9192311

**Comment by clapierre** [comment]
Placement is great @jkva but we need a little more white space around this button @jkva 
ALT: Search button practically overlaps with the search edit field, additional whitespace / padding needed.
![Screen Shot 2020-07-23 at 1 20 35 PM](https://user-images.githubusercontent.com/7736749/88335045-8808a100-cce7-11ea-80bf-bf93a2c1d9dd.png)

**Comment by jkva** [comment]
Strange, that didn't show for me. Will fix 👍

**Comment by jkva** [comment]
@clapierre is this by any chance CSS caching?

**Comment by clapierre** [comment]
Right again @jkva 
Sorry about that.
Thanks
