### ISSUE TITLE
Resource file Download buttons not vertically aligned due to resource name to the left of the button

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#191]
In order to hear the name of the resource and then the download button but always have the button positioned in the same location for multiple resource files in a single resource, lets move the "download" button under the name of the resource followed by its description if present.

Alt: Screenshot: example of new placement for download buttons.

![Screen Shot 2020-07-15 at 3 47 26 PM](https://user-images.githubusercontent.com/7736749/87609530-a3f0bf00-c6b7-11ea-8257-f7d79f3f74a2.png)

Is it possible to also keep all image thumbnails and icons the same width so that all the downloads light up vertically?

**Comment by jkva** [comment]
Implemented via e332cd2b74e0f1b11f61c63f2bd0c761ae922d6d
