### ISSUE TITLE
Editing a Resource file requires Description

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#193]
The Description field should be optional, now it is required if I want to update a resource file.
Please make this optional.

Alt: screen shot of WP Editing Resource File page : (red *) required by the Description field.
![Screen Shot 2020-07-17 at 9 04 15 AM](https://user-images.githubusercontent.com/7736749/87809753-bc282180-c810-11ea-854d-50b5dfc3ec73.png)

**Comment by jkva** [comment]
Implemented via 5a9fcb0463f1599b1f83b4042b0e8f3376cf81d6
