### ISSUE TITLE
When 0 resources / 0 collections are found

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#194]
Add after "No results matched your query."

the following:

"Not finding what you are looking for?  Try broadening your search by reducing the number of terms you are searching for.  You can also check out our FAQ on improving your search results.

Make the "FAQ on improving your search results a hyper link the the FAQ#improvedSearch.

We will add this to the FAQ.

**Comment by jkva** [comment]
Implemented via 0308dd7e639ce8e82815ccaca1f02d27351f503b
