### ISSUE TITLE
Missing "Clear Search" button when 0 results are found

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#195]
Button is missing as shown in the screenshot.

![Screen Shot 2020-07-20 at 9 44 28 AM](https://user-images.githubusercontent.com/7736749/87963560-bed38280-ca6d-11ea-8fd9-a4a224a41e5e.png)

**Comment by jkva** [comment]
Resolved via 0b6253256792a5cc8c016fa833877d48b341cedd
