### ISSUE TITLE
See More Collections: Page

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#199]
The "See More Collections" Page should look like the results of a "Search" instead of how "featured collections: are laid out on the Index page.

IE: clicking on the "See more Collections" from the index page should show the following view of Collections as shown in this snapshot (which is identical to doing a Search which matches all the collections we currently have)

![Screen Shot 2020-07-20 at 11 20 37 AM](https://user-images.githubusercontent.com/7736749/87972033-1b896a00-ca7b-11ea-94ff-ce0d13c7d4cc.png)

**Comment by jkva** [comment]
Implemented via f4d21615bfaaa0a4ec0c041a6f28b57a4756201b

**Comment by clapierre** [comment]
@jkva THANK YOU!!!

This is awesome, and will really help.
