### ISSUE TITLE
Report Issue link should include page user was on in email body

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#200]
When you click on the "Report Issue" and it creates a mailto email include in the body the page the user was on.

IE: (In body of email add)
Issue: (clickable Name of Resource)
Add additional information below.

Eg:
Issue: [Mars in a Minute: Is Mars Red Hot?](http://imgsdev.wpengine.com/btis_resource/mars-in-a-minute-is-mars-red-hot-dcmp/)
Add additional information below.

**Comment by jkva** [comment]
Implemented via a5ba7631732a7d375f96ab72ac71cee033139303

@clapierre clickable link is tricky without going full html-email. I've checked if it's done automatically by desktop mail clients but that doesn't seem the case. I've left it as a plain URL.
