### ISSUE TITLE
Search not searching "Author" field

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#204]
Should also include "Author" when using Search terms.

IE: Searching "Charles LaPierre" will find the collections I curated, but does not file the resource files I authored. Which should include the 

IE:
Frog Dissection (print, color, labels)-alt  Download
Author: Charles LaPierre

**Comment by jkva** [comment]
Resolved via 5f816f455e7774b66c79c7605bf53723dbd418b4
