### ISSUE TITLE
Search Results Page (Resource Links) not underlined

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#205]
The names of the resources which are links should be underlined to indicate they are links as shown in this screen shot.

<img width="1255" alt="Screen Shot 2020-07-20 at 3 07 32 PM" src="https://user-images.githubusercontent.com/7736749/87991548-4683b600-ca9b-11ea-9a7d-657c1b19e7c5.png">

**Comment by jkva** [comment]
Resolved via 15f61252ddaccd3e6865f58dda36a388b8de7790
