### ISSUE TITLE
Funky characters on Chrome with PC (Advance Search Arrows)

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#207]
Using Firefox our tester didn't have this same issue with the Up/Down characters showing correctly, so this seemed to be only an issue with the latest version of Chrome on Windows 10.

See screenshot with the Up/Down arrow for the Advance Search options displaying incorrectly.
alt: two screen shots showing the open/collapsed advance search with some random characters showing instead of the up/down arrows.
![Screen Shot 2020-07-21 at 1 54 34 PM](https://user-images.githubusercontent.com/7736749/88112964-b2caec00-cb65-11ea-8a67-9d1280ebb5f9.png)
![Screen Shot 2020-07-21 at 1 52 58 PM](https://user-images.githubusercontent.com/7736749/88112968-b52d4600-cb65-11ea-9e42-577eb2d39878.png)

**Comment by sinabahram** [comment]
Is this able to be replicated on other devices or consistently anywhere in incognito?

**Comment by clapierre** [comment]
This was on a PC @sinabahram in chrome on Jim Alan's computer so I can't really duplicate it here on my Mac, Chrome on Mac seems to work fine.

**Comment by jkva** [comment]
This is a strange intermittent loading problem. Not sure why it happens. I can try replacing the angle character with an svg.

**Comment by jkva** [comment]
Sorted via unicode in 033520b5c03617a7e657890d89797f2fe527a8ac
