### ISSUE TITLE
Add # of Resources found in a Circle (like we have for Files in a Resource)

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#208]
From our user testing they really liked when on a Resource page showing the # of resource files in a circle.
They want this same behavior on the Search results page for 
See modified screen shot with new # of resources and # of collections found with circle around them

![Screen Shot 2020-07-21 at 3 33 59 PM](https://user-images.githubusercontent.com/7736749/88114232-42719a00-cb68-11ea-82ae-055262f40d66.png)

**Comment by jkva** [comment]
Resolved via 79f2bb048ccd4a5b67c06099c564e42134d997d8
