### ISSUE TITLE
Increase the size of the "Download all files" Button on Resource Page

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#209]
User testing showed they missed this button since it it outside the list of the resource files with their individual download buttons.  User thought if this button was bigger (possibly as big as the H1 on the page this would help.

Alt: Screen shot of the "Download All Files (39)" button which we would like to be increased in size.

![Screen Shot 2020-07-21 at 3 39 57 PM](https://user-images.githubusercontent.com/7736749/88114502-d479a280-cb68-11ea-8272-26a1a0484697.png)

**Comment by jkva** [comment]
Implemented via 1a2fa790a5f98cb9bc4827f60a266c46b0b3a5f2
