### ISSUE TITLE
Re-importing does not re-index correctly

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#211]
When I re-import resources the resources and the resource files status becomes "pending review"
which is correct.

Going to the Resource View and selecting "Pending Resources" shows all pending resources to mark as published.

When I mark these as "Published" their associated files that are also "pending review" do not get published and as such no indexing occurs, and if I go to the resource files and mark all the Pending review files as "published" well they are published yes but not indexed by the resource so searching for 3D model doesn't find a resource with a file that has a 3D model in it.

This works for "new" resources because when I import a "new" resource it is marked as "draft" and its associated files are marked as "draft" and when I go into the Resource and change from "draft" to "published" both the resource and all its associated files all get published AND everything gets indexed correctly.

I even tried 'Re-indexing' like Sina suggested but this did not help.
The only workaround I could do is change all the "pending review" resources and "pending review" resource files all to "draft" and then go to the resources and edit their status now from "draft" to "published" which now behaves like a new resource and publishes both the resource and its associated files and reindexes correctly.

New resources and Pending resources when changed to "published" should mark all its associated files as published as well AND reindex.  I don't want to have to do all these steps to get the files republished.  
I just want to 
1. import the updated json file. 
2. Go to the "Pending review" for the all the newly imported Resources, and mark them all as "published".  

vs. what I have to do now which is 

1. import updated JSON file. 
2. mark all resource statuses from "Pending review" to status "draft" 
3. Mark all Resource files from "Pending review to status "draft"
4. Mark all Resource statuses from "draft" to "Published.

**Comment by jkva** [comment]
Fixed in 9e7f6de6afc5e6cc275014138b5b26b515407b95
