### ISSUE TITLE
Updated Timber Plugin

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#212]
Timber
You have version 1.16.0 installed. Update to 1.17.0. View version 1.17.0 details.
Compatibility with WordPress 5.4.2: 100% (according to its author)

I assume @johnhbenetech should update this?

Any objections @jkva or @sinabahram 

Both Dev & Staging.

**Comment by clapierre** [comment]
@johnhbenetech I can also do this as I have on the DIAGRAM WP website in the past, so let me know if you would rather me update these plugins.

**Comment by johnhbenetech** [comment]
@clapierre, i think it makes sense if you do it. Let me know if you run into any issues and I can see if I can help

If you ever need any paid plugins, let me know and I can deal with remitting payment

**Comment by jkva** [comment]
I'm good with it. The update runs fine on my development system 👍

**Comment by clapierre** [comment]
Thanks @jkva & @johnhbenetech 
upgrade complete
