### ISSUE TITLE
Image Type not showing up in search results

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#217]
We should also see the Image Type Icon show up in Search results.
Alt: screenshot of "Carbon Cycle" resource which has an JPG image and a Txt document but the Icon's for file types only show TXT, no IMG format.

<img width="1519" alt="Screen Shot 2020-07-24 at 11 46 03 AM" src="https://user-images.githubusercontent.com/7736749/88425033-86041800-cda3-11ea-9d8e-82ed99384621.png">

**Comment by jkva** [comment]
Implemented via 8faadea98fe31b1a48d78adcc807a23c6fa29799
