### ISSUE TITLE
Finding Resources and Resource Files in Wordpress 

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#218]
It would be great to be able to search for Resources by "Source", and Resource Files by "Author"

If we had an issue with a particular Source or Author of files we could easily find those and mark them as Private or Pending review for example.

Currently typing in "OpenStax" under Resources does not find any resources, and similarly typing in "Charles LaPierre" doesn't find any resource files by myself.

**Comment by jkva** [comment]
Implemented via 3aa735d03a28b8e118e252a96ede8b33e1dae619
