### ISSUE TITLE
New Issue in Resources / Resource Files in WP

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#220]
I re-imported the Frog Dissection that is in ticket #213 but now I am getting the same resource or resource file showing up multiple times in Wordpress, and I haven't yet even changed the status from all 50 resource files associated with this 1 resource.

See the screen shots below showing this weird new behavior.
Alt: Single resource "Carbon Cycle" now shows up multiple times instead of once
![Screen Shot 2020-07-26 at 5 17 56 AM](https://user-images.githubusercontent.com/7736749/88478835-31c27a80-cf00-11ea-9d01-f0dc8746e1d6.png)

Alt: in the (1 Pending) resource there is showing 63 resources instead of just the 1 pending
![Screen Shot 2020-07-26 at 5 18 22 AM](https://user-images.githubusercontent.com/7736749/88478881-7f3ee780-cf00-11ea-83a0-d2f5f4fccc7d.png)

And in the Resource Files (Pending) view instead of just the 50 resource files of Frog Dissection, I see other resources not related to this (ie. in the screenshot there is resource files from the little fish)

![Screen Shot 2020-07-26 at 5 19 41 AM](https://user-images.githubusercontent.com/7736749/88478908-b7462a80-cf00-11ea-8652-e67eb13ae1e5.png)

**Comment by clapierre** [comment]
I am wondering if this has to do with recent changes for either #213 or #167?

**Comment by jkva** [comment]
I suspect so. I'll have a look.

**Comment by jkva** [comment]
Should be sorted now. @clapierre can you check once this has deployed in a few minutes? cefccc4ddad0d9c6bee5cd4bf9592bbd72dd651b

**Comment by clapierre** [comment]
Yes this is now fixed, confirmed!
