### ISSUE TITLE
Resource Files Thumbnails should also be 1.5 times their size

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#221]
Sorry I thought this was part of the same issue #215, I didn't realize that it said only Search Results thumbnails, it was meant to be for the search results as well as the Resource View page.  The Resource page should also have its resource files thumbnails also at this 1.5 times the size of the thumbnails as they are very difficult to view.

**Comment by jkva** [comment]
I've increased the size in a4b4d180d892f4c0984ad9b4f4682ec02226135d -- can you check if that's to your liking?

**Comment by clapierre** [comment]
Perfect thanks @jkva
