### ISSUE TITLE
Low Vision Zoomed in Issue in Safari (Advance / Search) off-screen

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#222]
I can reproduce this on my Mac with Safari, Firefox and Chrome (Incognito).

On my Mac if you use Command + to increase the font size of the web page the accessibility accommodations start going off screen.
And at one point the Search button is entirely off screen.  If you keep increasing eventually the Search button wraps around to below the advance search options and at the maximum depending on your screen width all the advance search dropdown are vertical and all sown on the same screen.  But its the in-between larger font issue where we have items off screen as shown in these two screen shots.

Alt: Accommodation completely off screen.  Subject, Type and Search button are visible.

![Screen Shot 2020-07-27 at 9 49 30 AM](https://user-images.githubusercontent.com/7736749/88572532-29e40280-cff4-11ea-9e81-c81d3949aadd.png)

Alt: Accommodation partially off-screen.  Search button is only partially visible ("Se" is the only part of the button we see.)

![Screen Shot 2020-07-27 at 9 50 08 AM](https://user-images.githubusercontent.com/7736749/88572620-4bdd8500-cff4-11ea-9a62-901ac6a0deb9.png)

**Comment by jkva** [comment]
Should be sorted via 08351f498a5a043502a95e758ced0994a206dc1d.
