### ISSUE TITLE
Margins are a little too large

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#223]
Can we narrow the margins by 50%?

I think if we had a little less whitespace in the margins the advance search would fit on larger screen sizes.

See Screenshot of the abundance of white space on left/right margins

<img width="1677" alt="Screen Shot 2020-07-28 at 6 18 31 AM" src="https://user-images.githubusercontent.com/7736749/88671011-a3363080-d09a-11ea-80f6-34279a9510fa.png">

**Comment by jkva** [comment]
I've increased them a bit @clapierre. Let me know what you think.

**Comment by clapierre** [comment]
Actually @jkva I wanted the margins decreased in width, they are already too wide

**Comment by clapierre** [comment]
Oh looks like you did that sorry, my mistake.

**Comment by clapierre** [comment]
I think this works, Thanks.
