### ISSUE TITLE
Next Page/Last Page clears Search parameters

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#224]
When I do any search but for example say a search say for 2.5D Tactile Graphics

There are 34 results.
Page 1 shows results from 1-20.
When I click on the "Last Page" link I don't get the remaining 14 resource.
Instead I get 
Resources 2402
Showing resources 21 to 40 of 2402

and my previous search parameters are cleared which is why it is not showing me the next set of resources in my list.

Next or Last Page both have this same issue.

**Comment by jkva** [comment]
Added via ef4d1dba51f7756c82333ffa47d561716114129a
