### ISSUE TITLE
Missing our robot image in the header

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#225]
Not sure what happened but the Background image in the header use to have a robot in the top right corner.

It is now missing on Dev & Staging.

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (header.jpg, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (facebook.svg, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (twitter.svg, line 0)

**Comment by jkva** [comment]
Addressed via 984c9734b588d61b0da2c594841615028ef0661f

**Comment by clapierre** [comment]
I see the twitter and Facebook changes how come the background robot works now when you didn't adjust anything there @jkva ?

**Comment by jkva** [comment]
@clapierre separate commit. 891c9c1c00e72f054d4fb8d4f0f1ce517d751333

**Comment by clapierre** [comment]
Ah, should have figured ;) LOL
