### ISSUE TITLE
Accessibility of Terms of Service Agreement page

### ISSUE THREAD

**Issue by sinabahram** [benetech/ImageShare#228]
This page has a few accessibility issues.

* There are no headings in the content other than the h1 from the template. Proper use of headings needs to happen here.
* Lists are sometimes broken up for no discernible reason. For example two lists of seven items each are at the beginning of the agreement. It's unclear why this isn't a list of 14 items.

**Comment by clapierre** [comment]
All cleaned up @sinabahram 
You were right there were Headings which weren't marked up as H2's throughout.  Also the two lists was correct it just missed a heading which was included as the last item in the first list by mistake.
