### ISSUE TITLE
Accessibility of Search Results page

### ISSUE THREAD

**Issue by sinabahram** [benetech/ImageShare#230]
* Remove labelledby=main-search from the section tag.
* Also remove role="region" from the same section tag.
* Add aria-labelledby to the two pagination nav regions, pointing to their respective headings' ID.

**Comment by jkva** [comment]
@sinabahram done via db803f57ac8555a41e537bd7a2c04fcf0949a970. I didn't see a region role anywhere, though, so that might have been a glitch?

**Comment by sinabahram** [comment]
good stuff. thanks
