### ISSUE TITLE
Missing # of Collections

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#233]
On the "See More collections page"
We don't see the # of collections inside a blue circle like the other pages for # of resources or # of collections found matching the search.

Alt: screenshot of See more Collections page missing # of collections we have in our system.
![Screen Shot 2020-07-29 at 10 45 21 AM](https://user-images.githubusercontent.com/7736749/88836090-0bfcd600-d18b-11ea-8679-9f6ced4e0f4d.png)

IE: page = http://imgsdev.wpengine.com/collections/

**Comment by jkva** [comment]
Added via 0c91050b6edd6da68d313d4179a71d84ed71df35
