### ISSUE TITLE
Collections page missing pagination like Search Results Page

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#235]
In Search results there is pagination on the collections portion as shown here:
![Screen Shot 2020-07-30 at 5 58 32 AM](https://user-images.githubusercontent.com/7736749/88925847-f8ed1300-d229-11ea-9055-1bfe982f7fd7.png)

However on the "See more Collections page" we don't have this same behavior.
alt: missing collection pagination for this page: http://imgsdev.wpengine.com/collections/

![Screen Shot 2020-07-30 at 5 59 18 AM](https://user-images.githubusercontent.com/7736749/88925892-0bffe300-d22a-11ea-9d5f-c25f54c6ca32.png)

**Comment by jkva** [comment]
Are you expecting to have that many collections that you need pagination? It's kind of pointless without being able to search in them, which is what the search page does.

**Comment by clapierre** [comment]
I don't know how many we will have to be honest.  I guess we can always revisit this if it becomes an issue.
