### ISSUE TITLE
Footer: Benetech, IdeasThatWork, Facebook, Twitter Links don't go anywhere

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#236]
Facebook should go to:
https://www.facebook.com/Benetech.org/

Twitter should go to:
https://twitter.com/benetech

**Comment by clapierre** [comment]
Oh In addition the Benetech and Idea's that Work links also don't go anywhere in the footer.

Benetech Logo should go to:
https://benetech.org

Idea's that work should go to:
https://osepideasthatwork.org

**Comment by sinabahram** [comment]
@clapierre  this may be a good issue to verify hand-off, so would you like to do the commit that fixes this since it should be a one-liner in the template?

**Comment by clapierre** [comment]
Sure, I can do that, will see if I can find where that template is.  should be easy enough to find I hope :)
