### ISSUE TITLE
Accessibility page language

### ISSUE THREAD

**Issue by sinabahram** [benetech/ImageShare#237]
Can this please be reviewed. It's essentially a copy/paste from PAC's accessibility page, so at least a citation or reference would be necessary, but some of the items don't even apply e.g. we don't have slides on Imageshare, so this seems very problematic to me.

**Comment by clapierre** [comment]
Slides has already been removed.  How would you like this cited?

**Comment by clapierre** [comment]
I did review each item and made some changes as I went through although the slides statement was an over-site.  Happy to cite PAC @sinabahram , would you just like at the bottom (Accessibility statement derived from PAC's accessibility Statement found here. and link to that?

**Comment by clapierre** [comment]
Added to top of our page: 
Accessibility statement derived from PAC's accessibility statement found here. which links to your accessibility statement.

**Comment by sinabahram** [comment]
Closing this, but please note that the contact us links point to an absolute URL, which is not a good idea especially since right now they go to the old Imageshare site, but also because any future migrations of URL, staging to prod, etc. will all fail to respect whatever environment their in. Everything should be a relative link. Some links may appear absolute, but WP is the one generating them, so they'll be generated correctly, just phrased absolutely; however, those not automatically generated should be relative, IMHO. Just flagging that.
