### ISSUE TITLE
WP Fulltext Search Plugin - Update breaks Imageshare

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#239]
When I installed
WP Fulltext Search
Version 1.28.75
This was with WP 5.4.2 

Search completely broke and I would get 0 results for any search performed.
I have reverted Dev back prior to the plugin update.

(BTW: there is a new WP 5.5 which I will test an see if this resolves the problem)

**Comment by jkva** [comment]
Make sure to force a reindex as well.

--
Job van Achterberg | 3ode
Middeldiepstraat 51 | 3361VR Sliedrecht | http://www.3ode.nl
M: 06 46 77 80 60 | E: mail@3ode.nl | KvK: 63716348

**Comment by clapierre** [comment]
Oh that is a good point ;). Will try that.

**Comment by clapierre** [comment]
Ok, So after installing the new Plugin and doing a full reindex
Search is working after I adjusted the settings from OR to AND.

However I did notice something in the 
STEP #3: Calculate Relevance
In the old version there are the following which I don't know how to add in this version.  There doesn't seem to be a way to add anything


Weight	Cluster Name
	post_title 0 
	post_content 0.5
	btis_collection_accommodation 0.5
	btis_collection_child_content 0.8
	btis_collection_data 0.5
	btis_collection_subject 0.5
	btis_collection_type 0.9
	btis_resource_accommodation 0.5
	btis_resource_child_content 0.5
	btis_resource_data 0.5
	btis_resource_file_data 0.5
	btis_resource_subject 0.5
	btis_resource_type 0.5

So how do we add these back?
	
there is a mention of: "Cluster" is a part of post (either title, content or even specific part which you can define using wpfts_index_post filter). You can assign some relevance weight to each of them.

**Comment by jkva** [comment]
Those are added by the indexation process. I just went to check and they're there - are you not seeing them?

**Comment by clapierre** [comment]
Ok, either a timing issue or caching issue but yes, I do see these and its working now as expected.  thanks!
