### ISSUE TITLE
Unable to manually add resources through wordpress "Add" (thumbnail image is blank)

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#241]
Unable to See Resource Featured Image URL when adding a resource manually.  

All the resources so far has been imported using the Settings/Import tool and this worked for the featured Image of the resource.

However when you go to edit any of those resources added via the JSON import the 
"Featured Image URL" is blank as shown in this screen shot.

![Screen Shot 2020-08-20 at 7 29 12 AM](https://user-images.githubusercontent.com/7736749/90785666-70f1aa80-e2b7-11ea-8893-e3ca455ff5d3.png)

Now when I added a new resource manually and added in the URL to the featured image is shows in this "Featured Image URL" as shown in this screen shot

![Screen Shot 2020-08-20 at 7 29 12 AM](https://user-images.githubusercontent.com/7736749/90786206-258bcc00-e2b8-11ea-8299-e60615f73248.png)

However the Thumbnail image doesn't show up.  I have tried both URLs to our S3 images as well as ones which we used for the DCMP video thumbnails all of which showed correctly so its not an issue with how we are storing the images on S3 (ie. downloadable/preview-able).

As you can see here and when I find the Resource in Imageshare it also shows a blank thumbnail for any image where we manually added resource vs. imported it from the plugin settings.

Alt: Wordpress Resource View, shows this resource has no thumbnail image
![Screen Shot 2020-08-20 at 7 28 57 AM](https://user-images.githubusercontent.com/7736749/90786919-0477ab00-e2b9-11ea-91ae-f7544052edf2.png)

Alt: Imageshare Resource View, shows this resource has no thumbnail image
![Screen Shot 2020-08-20 at 7 42 38 AM](https://user-images.githubusercontent.com/7736749/90787025-28d38780-e2b9-11ea-857b-71ba3f06c35e.png)

(Also checking the page source has the following)
<img src="" alt="Screenshot: Phet Simulation - Ballons and Static Electricity.  Sweater with number of + / - balls representing protons and electrons on the shirt.  Ballon with a few + / - balls  on it, and a wall with a large number of + / - balls." class="thumbnail"/>

**Comment by jkva** [comment]
Fixed via 71e65f5
