### ISSUE TITLE
Featured Collection images are blurry

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#242]
I didn't notice this before but when I added the new "PHet Simulations" collection it was very obvious that the Featured collection images are fuzzy even though there is high res images uploaded in the media collection.

See the screen shot with the fuzzy collection images:
![Screen Shot 2020-08-20 at 12 23 20 PM](https://user-images.githubusercontent.com/7736749/90815813-20db0e00-e2e0-11ea-8696-771ed08857a5.png)

as compared with original Phet Simulation Image

![SimulationPortrait](https://user-images.githubusercontent.com/7736749/90816025-731c2f00-e2e0-11ea-99e9-ded4066d5360.jpg)

**Comment by jkva** [comment]
That's probably WordPress thumbnail generation.

**Comment by jkva** [comment]
I'll see if I can configure the browser to pick from a set of images to improve the resolution.

**Comment by jkva** [comment]
Implemented via efeb11a744f1d722c2131bef453fefb12ea70df1
