### ISSUE TITLE
Upgrade WP 5.1.1

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#245]
@johnhbenetech should we upgrade to WP 5.1.1?

https://wordpress.org/support/wordpress-version/version-5-5-1/
We can test on Dev first.  We have a new backup already as I pushed what we have to Staging this morning.

**Comment by johnhbenetech** [comment]
@clapierre I think as a general policy it's probably fairly safe to do maintenance updates (v5.1.X) on dev to do a smoke test before release.

I think we should be cautious on feature releases (v5.X) and then super afraid of major (v6.0) releases

**Comment by clapierre** [comment]
Makes sense!

**Comment by clapierre** [comment]
Complete along with latest plugins.
