### ISSUE TITLE
Print on Demand

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#246]
We want to have the ability to Print 3D and potentially 2D tactile graphics indirectly from Imageshare.  For those Resource Files that can be printed there will be a new field associated with these resources that would contain a URL to some 3rd party page where the user can request as many copies of the image/3D model they want printed and have it shipped to them.  The 3rd party will handle all the logistics of printing, shipping and payment costs if any.  All Imageshare has to do is point to a specific URL provided by the 3rd party for the associated Imageshare resource file to be printed.

NOTE: Not all 3D models or 2D tactile images will have this feature so only those we specifically add the URL to that file resource.

file_PrintURI [Optional] (Link to external Printing page)

This file_PrintURI will be a new optional field in our Excel spreadsheet, which will convert to PrintURI in the "files" section of our JSON schema.

PrintURI will also show up as optional fields in both the "Add New" and "Edit" Post for a resource file.

When PrintURI is not empty a new Button (styled the same as all Imageshare Buttons in the system) will show up beside the "Download" or "Visit" button.  If there is a "Preview" button also being displayed this new button will appear to the right of both "Download/Visit", "Preview" and then "Print".

Button Label will be "Print" the Aria-Label can say "Print (Resource Name" similar to how "Visit" or "Download" currently behaves.

If we need to have some additional Screen Reader text stating that they will be taken to a 3rd party website we should add that as well to the aria-label if necessary.  If we need some visual indication that pressing this button will be taken to some 3rd party website then we should do the same thing to the "Visit" button.

When pressing this button this new webpage should be brought up in its own new tab.

**Comment by jkva** [comment]
Hi @clapierre, given the term "Print" being somewhat ambiguous, I would propose two fields:

`print_service` such as "Kinkos 3D"
`print_URI` (as proposed in this ticket)

That way we can render a link that says "Order 3D print at Kinkos 3D", which explains why it's there and what it's for.

**Comment by clapierre** [comment]
This is a great idea, since we may have 2D going to some other place etc.

**Comment by jkva** [comment]
Implemented via 128abebdc28c71971d525efb625dee653dd31815

**Comment by clapierre** [comment]
I don't see
Print Service 
nor
Print URI
when editing a Resource File
![Screen Shot 2021-01-07 at 7 36 54 AM](https://user-images.githubusercontent.com/7736749/103911981-92fb9600-50bb-11eb-8992-2cc2b70e14d3.png)

**Comment by clapierre** [comment]
I would also expect to see under
benetech/Imageshare-utils/scripts
changes to 
tsv2json.py 
to support these two new fields

**Comment by jkva** [comment]
> I don't see
> Print Service
> nor
> Print URI
> when editing a Resource File
> ![Screen Shot 2021-01-07 at 7 36 54 AM](https://user-images.githubusercontent.com/7736749/103911981-92fb9600-50bb-11eb-8992-2cc2b70e14d3.png)

The custom fields hadn't been imported on the dev instance, this is sorted now.

**Comment by jkva** [comment]
@clapierre from what I can tell in the util script, most column names are mapped to the JSON automatically. So as long as the csv contains a `print_service` and `print_URI` column, all should be well.

**Comment by sinabahram** [comment]
Note, though, that once those columns are added, indexes may need to be changed.

**Comment by clapierre** [comment]
@jkva similar here all resource files have as the excel column name starting with file_
So would these be

file_Print_Service
file_Print_URI
or
print_Service
print_URI

I would think file_*

**Comment by sinabahram** [comment]
Yes, prefix with file

**Comment by clapierre** [comment]
Implemented in Imageshare-utils/Scripts/tsv2json.py
and testable using

Imageshare-utils/Data Files/Matter Hackers/prototype-matterhackers-Imageshare.txt & associated xls and json files

Imported this json file and is working currently 
http://imgsdev.wpengine.com/btis_resource/3d-printed-protective-face-shield-matter-hackers/

**Comment by jkva** [comment]
Closed as reportedly working as needed.
