### ISSUE TITLE
Resource Source optional Link to the original source of this resource

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#248]
We want to have the ability to go to the original source of this resource.

For example if a particular 3D model came from Thingiverse a link to that on Thingiverse would be useful as it may have additional information regarding this resource that we don't yet have.

NOTE: Not all resources may have this feature so only those we specifically add the URL to that source's resource.

resource_sourceURI [Optional] (Link to external source for this resource)

This resource_sourceURI will be a new optional field in our Excel spreadsheet, which will convert to sourceURI in the "resource" section of our JSON schema.

Source URL will also show up as optional fields in both the "Add New" and "Edit" Post for a resource.

When SourceURI is not empty the Source Name of the resource will become a clickable link to the webpage provided in the SourceURI.
When pressing this link this new webpage should be brought up in its own new tab.

EG:
http://imgsdev.wpengine.com/btis_resource/t-rex-thingyverse/
On our Page instead of (Source: Thingiverse) as just plain text it would be clickable as shown here.

[(Source: Thingiverse)](https://www.thingiverse.com/thing:308335)

**Comment by jkva** [comment]
Implemented via 78ab29c8854ded578a2108f99b2fcd7a89318cd4.
@clapierre for consistency with other field names in JSON, this field is named `source_URI`.

**Comment by clapierre** [comment]
I would also expect to see under
benetech/Imageshare-utils/scripts
changes to 
tsv2json.py 
to support this new Source_URI

**Comment by jkva** [comment]
@sinabahram up till now you've been taking care of `tsv2json.py`; are you still expecting to make changes to this? Otherwise I'll happily take care of things for this issue and #246.

**Comment by sinabahram** [comment]
@jkva  if you wouldn't mind, I would greatly appreciate it. Cycles are hard to come by over here, and the change is a few minutes at most.

Thank you in advance.

**Comment by jkva** [comment]
Sure thing. Will take care of both tomorrow.

**Comment by jkva** [comment]
@clapierre similar to https://github.com/benetech/Imageshare/issues/246#issuecomment-760197129, this should be happening automagically as long as a column in there is `source_URI`.

**Comment by clapierre** [comment]
Ok I will give it a try today and see if that all works as expected then.

**Comment by clapierre** [comment]
So @jkva question for this would the new column be?
source_URI
or
resource_source_URI

All other resource level columns have resource_ in front in the excel spreadsheet

**Comment by sinabahram** [comment]
Please prefix with resource

**Comment by clapierre** [comment]
Implemented in Imageshare-utils/Scripts/tsv2json.py
and testable using

Imageshare-utils/Data Files/Matter Hackers/prototype-matterhackers-Imageshare.txt & associated xls and json files

Imported this json file and is working currently 
[http://imgsdev.wpengine.com/btis_resource/3d-printed-protective-face-shield-matter-hackers/](http://imgsdev.wpengine.com/btis_resource/3d-printed-protective-face-shield-matter-hackers/)

**Comment by jkva** [comment]
Closed as reportedly working as needed.
