### ISSUE TITLE
Editing Resources contain blank Featured Image URI

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#251]
When I go to Edit an existing resource the field

Featured Image URI is blank.
It should be populated with the URI to the Amazon S3 bucket image we have previously set.
![Screen Shot 2021-01-07 at 7 25 08 AM](https://user-images.githubusercontent.com/7736749/103910716-02708600-50ba-11eb-962c-0432f88c7e6e.png)

**Comment by jkva** [comment]
@clapierre I'm unable to reproduce this on the dev instance, not for this particular resource or another. Is this still happening for you?

**Comment by clapierre** [comment]
So weird yes it is working now, no idea why it was blank before.  Maybe when you reindexed for Print Services it fixed this.
