### ISSUE TITLE
Discuss API Documentation Strategy

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#252]
Maybe a Github action to keep documentation up to date
...

**Comment by sinabahram** [comment]
@jkva  can we discuss in this ticket the approach we are using for the JSON API documentation. @johnhbenetech  I'd like to hopefully do this in such a way that it is automatically generated for you via a GitHub action, but let's discuss that once Job updates us on documentation approach.

**Comment by jkva** [comment]
I would suggest I write a yaml spec of the OpenAPI implementation the server follows - such as seen on https://editor.swagger.io/. This can then be used to generate similar documentation.

**Comment by sinabahram** [comment]
@johnhbenetech  you good with the above?

**Comment by johnhbenetech** [comment]
@sinabahram @jkva works for me

**Comment by jkva** [comment]
The current implementation has been written to follow [the json-api spec](https://jsonapi.org/); Swagger speaks `openapi`. While I could modify the request/response cycle to implement `openapi` instead, it's currently an fairly simple read-only api. Moving to another spec seems overkill. I've added documentation in the main plugin README for now, eventually this might move to its own separate markdown file and be linked to from the main README.

**Comment by jkva** [comment]
Following up; if autogenerating documentation is a strongly desired feature, I can modify things accordingly to implement an `openapi` compliant api. But given the current simplicity of the API I wonder if that's needed. @johnhbenetech what do you think?

**Comment by johnhbenetech** [comment]
@jkva README seems adequate. I don't imagine this changing frequently and significantly, so shouldnt be too much of a hassle.

**Comment by jkva** [comment]
Closing as adequately addressed.
