### ISSUE TITLE
All resources now showing duplicate files on Dev

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#253]
I assume this is a side effect from current work on groupings, but thought I would point it out.

Alt: screenshot Imageshare Dev showing there should be 1 file yet the same resource file is duplicated twice.

![Screen Shot 2021-01-14 at 11 01 16 AM](https://user-images.githubusercontent.com/7736749/104636274-f5263f00-5657-11eb-9ea7-84ff62f4e9ad.png)

**Comment by jkva** [comment]
Yes, it was. Thanks for the catch - fixed in c398434219e3c50ccdfe69c4390d0880e6b46e0a.
