### ISSUE TITLE
Various endpoints don't list results in alphabetical order

### ISSUE THREAD

**Issue by jkva** [benetech/ImageShare#256]

**Comment by jkva** [comment]
@clapierre this seems a nice-to-have; explicit sorting parameters aside (when contextually sensical), I'd expect a consuming client to take care of its sorting needs - agreed?

**Comment by clapierre** [comment]
Yeah thats fine at this point.

**Comment by sinabahram** [comment]
Closing, and also noting this was a requirement we added just to make the extension's life easier, so no loss of functionality what-so-ever as a result of not having it. Also, less load on the server per call.
