### ISSUE TITLE
Update new Imageshare Main Logo to match Extension Icon

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#259]
This replaces the current Imageshare Icon on all the pages in the top left corner.

![Imageshare-logo-new](https://user-images.githubusercontent.com/7736749/111361027-a9d5e000-864a-11eb-8abf-b4b5362082c7.png)
alt="Logo: Imageshare - A Benetech Initiative"

**Comment by jkva** [comment]
Implemented via https://github.com/benetech/Imageshare/commit/de50c74ed57aa81fa8539bdcf6b5ffb8b3c650ec
