### ISSUE TITLE
Accessibility UI Design Review

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#26]
Work with Sina to review the new UI/UX Mockups from Deanna to ensure accessibility.

[https://96i7ux.axshare.com/home.html](https://96i7ux.axshare.com/home.html)

**Comment by clapierre** [comment]
@jscholes Is this complete now?  I think this was broken up into #66 #67 #68 correct?

**Comment by sinabahram** [comment]
Yes, I'm closing this as those tickets address the work we did to synthesize accessible designs, and for the review portion, we've also already delivered that.
