### ISSUE TITLE
Single ID requests don't work for some entities

### ISSUE THREAD

**Issue by jkva** [benetech/ImageShare#260]
> The single ID requests (e.g. /json-api/accommodations/171) don’t seem to be working for the following entities:
> ·         Accommodations
> ·         Sources (non numeral ID, but doesn’t work with text id)
> ·         Keywords

This is to be expected; there is no relational information or otherwise other information available for these types of entities.

What _could_ be added is a relationship for resources associated with the particular [accommodation, source, keyword]. Is that desired?

**Comment by johnhbenetech** [comment]
Understood, won't fix
