### ISSUE TITLE
Implement term filters in resource endpoint

### ISSUE THREAD

**Issue by jkva** [benetech/ImageShare#261]
As remarked by @johnhbenetech:

> I’m having some issues using the format and type filters for resources. No matter which values I put in (even garbage) I still just get everything returned?

These filters are currently not implement and should be.

**Comment by jkva** [comment]
@johnhbenetech you can now filter resources by subject, type, accommodation and source. Format was never a supported search filter. Can you check whether the behaviour is as you expect?

**Comment by sinabahram** [comment]
Assuming this is good to go. Closing for now.
