### ISSUE TITLE
Don't expose unpublished resources via resource API endpoint

### ISSUE THREAD

**Issue by jkva** [benetech/ImageShare#262]
As remarked by @johnhbenetech :

> While unpublished resources don’t appear in the filter results, they are reachable by directly hitting the ID. Charles, this is more of a question for you – should we expose unpublished things? The IDs are incremented so are easily guessable.

**Comment by clapierre** [comment]
Unpublished items if guessed by their IDs should not be shown.

**Comment by jkva** [comment]
@clapierre I expected as much, hence the presumptuous issue title ;)

**Comment by jkva** [comment]
Addressed via 0f47461d28c87f4bfd381a385174b2ef974e1da6
