### ISSUE TITLE
Sources endpoint uses non-numerical IDs

### ISSUE THREAD

**Issue by jkva** [benetech/ImageShare#265]
As remarked by @johnhbenetech:

> The non numeral ID for Sources entity is a bit weird. I haven’t tested various collision possibilities, case sensitivity, null values, etc. but doesn’t seem like a big deal honestly.

This is the case because the source isn't a taxonomy term as the others (accommodations, subject, format...) are; it's a distilled set of unique sources used within imageshare. The _source_ field is a free text field.

The ID is generated via some normalisation.

```php
public static function normalise_id($source) {
  return strtolower(
    preg_replace('/_{2,}/', '_',
    preg_replace('/[^\w]+/', '_',
    preg_replace('/\s+/', '_',
      $source
))));
```

It's not really used for anything apart from having an ID to render to JSONAPI spec. The ID isn't used anywhere.

**Comment by johnhbenetech** [comment]
Sounds good. Wont fix
