### ISSUE TITLE
Weird data being returned by files endpoints

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ImageShare#266]
I'm noticing some strange data getting appended in front of the JSON object on the files endpoints, some examples:

- [double zeros appear in front](http://imgsdev.wpengine.com/json-api/resources/18857/relationships/files/)
- [the phrase '20 minutes' appears in front](http://imgsdev.wpengine.com/json-api/resources/18659/relationships/files/)

**Comment by jkva** [comment]
Nice catch! Fixed via 025ec77.
