### ISSUE TITLE
Focus Outline Improvements

### ISSUE THREAD

**Issue by sinabahram** [benetech/ImageShare#269]
Tagging in @jkva  for this.

Thanks go to Lauren for these two sugestions.

1. For \<button\> and \<input\>: add an offset to the current focus outline and effect a change in the background color of the button to increase visibility. It may be useful to add offset in other areas as well to ensure the outline doesn't obstruct whatever it's highlighting.
2. For \<li\> with role = option: add a bottom border to current background change on focus so indication is not by color alone.

**Comment by jkva** [comment]
Done via bdf272cc064edfe8975d09923aeb513064e2c0de and f84a9d786bfae2a9e84a4c990171218337281563
