### ISSUE TITLE
Create Backend Database to store Resources both internal / External with provided taxonomy

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#27]
See Word Doc attachment for general Database & Taxonomies.  I realize that this is not in Wordpress format so there will be some adjustments need to be made here.
[Imageshare MVP Database Taxonomy.docx](https://github.com/benetech/Imageshare/files/4475887/Imageshare.MVP.Database.Taxonomy.docx)

**Comment by sinabahram** [comment]
Closing this ticket because it is now handled by #32 and #33
