### ISSUE TITLE
Change keywords to tags in the UI

### ISSUE THREAD

**Issue by sinabahram** [benetech/ImageShare#270]
This is a simple change, but can we please bring the UI into alignment wit the spreadsheet, script, and backend language around this concept?

All that needs to happen is that in the template, the word keywords needs to be change to tags wherever appropriate.

**Comment by jkva** [comment]
Yeah, this was in my mental to-do. Fixed via 2f358326ec2969dd29915dad50b6e6c5939ed2d7.
