### ISSUE TITLE
Create /search-terms endpoint

### ISSUE THREAD

**Issue by sinabahram** [benetech/ImageShare#271]
1. /search-terms should return the union of all tags and all words in all titles of resources that are greater than 3 characters long. This means all tags are included independent of length, and all words from titles that are 4 letters or longer as well.
2. Each entry in this list must obviously map to a location on Imageshare. That way, the resulting dialog that comes up in the browser knows where to send people when they hit enter, click OK, etc.
3. It is absolutely fine to either regenerate this any time a title changes or tags are added, or honestly if it is easier, do it nightly.

**Comment by sinabahram** [comment]
See related issue on the extensions repo:
https://github.com/benetech/imageshare-extensions/issues/26

**Comment by jkva** [comment]
To clarify -- only titles, not content and associated file titles and content?

**Comment by sinabahram** [comment]
Yes, that's right. That's how we're controlling for accuracy/relevancy.

**Comment by jkva** [comment]
This is currently implemented as a simple keyword list to run intersections against. Any enhancements to this endpoint will be covered by separate tickets.
