### ISSUE TITLE
Dev website 4x times slower than Staging

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#272]
I noticed this a while ago, and was hoping it would get better once everything was indexed etc, but this seems to be still a pretty big problem.
On the [Development website](http://imgsdev.wpengine.com) it takes ~12 seconds to find "frog"
On the [Staging website](http://imgsstaging.wpengine.com) it takes <3 seconds to find "frog"

Can we look into why we are taking so long now?
I just went and upgraded the Staging server to the same Plugin versions for both Custom Fields and WP Fulltext Search, and there was no difference in speed on the Staging it still is 3-5x faster than after upgrading to the same version as Development.

I also rebuilt both search indexes just to be sure and the same speed difference exists, so something else is causing the slowdown in Development server.

**Comment by clapierre** [comment]
Once it's cached it seems very quick to return the same results, but searching for new words seems to take anywhere from 6 to 13 seconds as compared to usually under a second on staging.

**Comment by clapierre** [comment]
BTW, both dev and staging are at WP 5.6.2

**Comment by sinabahram** [comment]
We did repeatedly warn about this RE WPEngine, not sure what the ask is here?

**Comment by clapierre** [comment]
Well the same WP engine is running development and staging with the same plugins, so did we do something now that is slowing down search by a factor of 5?

**Comment by sinabahram** [comment]
@johnhbenetech  my understanding is that dev has seriously limited resources. Is this correct, and does staging have the same limitations? Is production the only place where we get full resources?

**Comment by johnhbenetech** [comment]
@sinabahram @clapierre I agree this is a WPEngine thing. So nothing to do on the code side of things.

My understanding is that staging and prod should be full power.

I'll ping WPengine to see if they can boost our dev, but i'd say we can deal with it on dev and then demo on staging.

**Comment by sinabahram** [comment]
Thanks @johnhbenetech 

@jkva  note the slow downs are still there, independent of increased resources, so don't want John's comment to detract from that immediate need to resolve that issue.

**Comment by johnhbenetech** [comment]
@sinabahram @clapierre I guess I assumed that we were using the same imageshare plugin version on all environments for this speed comparison. That doesnt seem to be the case as dev is running v1.1 and staging is 0.0.1.

In addition I reached out to wpengine, and they state that all 3 environments have the same configuration and resources (the only exceptions are any custom redirect, cache exclusions or Nginx rules).

So i guess this may actually be imageshare related but maybe @clapierre can test updating staging to the latest imageshare version and test again

**Comment by clapierre** [comment]
I did push the latest dev over to staging @johnhbenetech as a test with Sina an hour ago and had the same slow results, so we are now thinking its a change we made with our new custom object for File groupings which may not be indexed correctly.  Hopefully @jkva can track down this issue.

**Comment by sinabahram** [comment]
Thanks for that, but for what it is worth, I can with 100% certainty say that dev does not have same resources as production. I have verified that across multiple client projects.

**Comment by jkva** [comment]
It's a strange issue. I have searches respond almost instantly on my local development instance (which is not that beefy either) on a copy of the database, yet the dev instance is noticeably slower.

I've also noticed a significant slowness in building the search index - 20 minutes on dev compared to 6 minutes on my local instance.

**Comment by jkva** [comment]
For example, a heavy search result for the term "science" takes a few seconds on dev, and is pretty instant on my local install. Which makes it tricky to debug - I have no terminal access on the dev instance.

**Comment by jkva** [comment]
Investigated some more - found something that might be related where more resources are processed for display then are actually being displayed. I'll try to sort these out this week.

**Comment by jkva** [comment]
It seems the WordPress built-in meta-data querying is the culprit as far as query speed is concerned - it is known to be slow. I might need to address this by generating optimised querying tables.

**Comment by clapierre** [comment]
Not sure why now but searching on DEV Front end it always is slow now.  Very odd which seems different than what I experienced yesterday. If I search for "frog" it takes ~12 seconds or so, previously on the same browser I would search again and it would be instant, now each search for "frog" takes ~12 seconds.

The only exception to this which is quite odd (maybe a chrome caching) is in chrome when I search for frog (12 seconds) then click on the Imageshare Icon going to the home page and search for frog again its instant, however if I click on the "Clear Search" button then search for Frog again its again 12 seconds to find it.  So I think this is what I was experiencing yesterday and still do now.

Also @jkva incase it provides any insight into this but on the backend when I click on the following in the Admin pane (every time not just the first time):

"resources"  ~12 seconds 
"resource files" ~36 seconds
"file groups" ~ 2 seconds
"collections" ~2 seconds

On the Staging server with the same amount of data (just not with our new file groupings code) each of those only take ~2 seconds.

**Comment by jkva** [comment]
@clapierre thank you. I've narrowed down most of the speed impediments and am working on some optimisations. I hope to deploy those on the development server over the next day, two days. Local tests have heavy queries such as "science" (3239 resources, 7 collections) return in 2-3 seconds, other smaller ones ("frog", "animals") are instant. I'll keep you posted.

**Comment by jkva** [comment]
@clapierre I've made multiple speed optimisations. It should perform significantly faster now. Please give it a whirl and let me know what you think.

A good heavy query is "science", in my experience.

**Comment by clapierre** [comment]
AWESOME!  This is working like it use to.  
Well done!

**Comment by clapierre** [comment]
Tested both backend and front end and both are working as expected!
