### ISSUE TITLE
Firefox on Mac with Voiceover skip links not working

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#273]
I am not sure what is going on here, I noticed this when testing the Extensions today but in Firefox when you get to a resource page and we have the two links
"Skip to matching resources" and "Skip to matching collections" when I click on them with Voice Over Space to activate the link it moves the viewport to where it should but the focus stays on the link.

This may be a Firefox bug with voice over on a Mac but thought I should mention it.  It works fine with Chrome and Safari, but this was just very bizarre and happens in both Firefox and Firefox dev.

**Comment by sinabahram** [comment]
Closing this because Firefox+VO is not something we support. That's not an official combo. VO+Safari is good on Mac. VO+Chrome is usable, but not something I would ever claim officially works. VO+Firefox is even less than VO+Chrome. On Windows, it's Jaws/NVDA with Chrome/Firefox.
