### ISSUE TITLE
Implement migration strategy for orphaned resource files

### ISSUE THREAD

**Issue by jkva** [benetech/ImageShare#276]
Scenario:

1) a group gets deleted
2) IF it is the default group for a resource, the resources it contains become freed.
3) IF it is a non-default group for a resource, the resource it contains are moved to the default group for the resource.
3a) IF the resource has no default resource group, the resources become freed.

**Comment by jkva** [comment]
Implemented via 63f4de8ddfff3bb6b31483307d10a53e8725618c

**Comment by clapierre** [comment]
I just deleted a group and the 6 files in that group didn't get automatically added back to the default group unfortunately.

Going now in manually and searching for those 6 adding them back to the default group.

**Comment by jkva** [comment]
And the group that was deleted was not the default group and otherwise shared the same parent resource?

**Comment by clapierre** [comment]
Correct this was a child group for this resource.

**Comment by jkva** [comment]
Surprising. I ran some successful removals earlier today where the files were migrated. Please hold off for now - I'll have an in-depth look this Thurs.

**Comment by clapierre** [comment]
Ok I just tried again with Chrome and it worked.  maybe some issue with Safari with Wordpress some weird thing there.
This is working it seems.
