### ISSUE TITLE
Create initial landing page with Search field and stub for curated collections

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#28]
This should initial Home/Landing page should [look similar to the Mockup](https://96i7ux.axshare.com/home.html)

The attached image of the Robot for the main background image for the top of this page
![robot crop](https://user-images.githubusercontent.com/7736749/79260837-c3bbe100-7e43-11ea-8de1-b0f6ec355b98.jpg)
This is really a decorative Image, can discuss with Sina if we need to include alt-text for this image or not.

There should be a skip to main content Accessible Link hidden visually (if required)

We will have appropriate Heading Levels
H1 - Library of Accessible Educational Resources
H2 - Explore Collections
H2 - Search

There is the footer with links which will be discussed in a separate ticket.

**Comment by sinabahram** [comment]
Closing because now handled in #34, #35, #36, and #37
