### ISSUE TITLE
Team agrees to the initial list of plugins to use

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#32]

**Comment by clapierre** [comment]
@jkva I would think we would be working on this currently right?  Haven't we finalized which plugins we will need already?  can we list them also in this ticket before closing please.

**Comment by jkva** [comment]
@clapierre Agreed.

## Plugin:

* Advanced custom fields, for administration, managing resources, resource files and collections - https://wordpress.org/plugins/advanced-custom-fields/

* Smackcoder's CVS import plugin (paid) - https://wordpress.org/plugins/wp-ultimate-csv-importer/

## Theme:

* Timber - https://wordpress.org/plugins/timber-library/

**Comment by sinabahram** [comment]
Also, Charles, I wish to note finalizing this list is not blocking other ImageShare work just yet. For example, ACF is a given, IMHO, but the CSV importer is one I wish to discuss with Job.

 

Let’s definitely finalize the list by end of day on Friday.

 

As for the list being in the ticket. I totally agree.
