### ISSUE TITLE
Implement Search

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#34]

**Comment by sinabahram** [comment]
#### Search Criteria
* Initially Search will use only resource's Title and resource's tags. We may need to expand this to also include resource's Description if we find we are not getting the desired results.
* Search will initially be limited to "Whole Words only" so we don't get "heart" when you search for "ear". Ideally searching for "ears" will find "ear" or searching for "ear" will find "ears". If substring matching is required, that will be discussed in a new issue.

**Comment by sinabahram** [comment]
Here are some search plugins that may be of use. It would be good for us not to  roll our own search functionality, or at least to have a good reason for doing so if we go that route. These are in no particular order.

* [SearchWP](https://searchwp.com/)
 * [SearchWP Live Ajax Search](https://wordpress.org/plugins/searchwp-live-ajax-search/)
  * [WP FullText Search – The Power of Indexed Search](https://wordpress.org/plugins/fulltext-search/)
* [WP Custom Fields Search](https://wordpress.org/plugins/wp-custom-fields-search/)
* [Relevanssi – A Better Search](https://wordpress.org/plugins/relevanssi/)
* [Search & Filter](https://wordpress.org/plugins/search-filter/)

**Comment by jkva** [comment]
Implemented via e4af8468fb30e60dba32b786a7175a849a89bc34
