### ISSUE TITLE
Integrate search on Landing Page

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#35]

**Comment by sinabahram** [comment]
From the home page users can search for specific types of resources by entering text and have the option of narrowing the search criteria by choosing:

1.  specific subject area,
2. Resource Type,
3. and / or accessibility accommodation.

**Comment by sinabahram** [comment]
This is done. Note, search is not done yet, but it is integrated on landing page. Other issues pertain to search's operations.
