### ISSUE TITLE
Create Resources

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#38]
Important to keep in mind when a concept of a Resources is being created it have a Field for Featured Image.

**Comment by clapierre** [comment]
Should be easy to change afterwards to a new featured image.

**Comment by sinabahram** [comment]
@jkva   I think this is done but it is still open and there is no commit linked against it. Can you please link a commit against this and close if you agree?

**Comment by jkva** [comment]
Implemented via 1735d04cd647e41b7008c4fcea7f2d49f48f75c5
