### ISSUE TITLE
Create Header for Website

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#39]

**Comment by sinabahram** [comment]
@clapierre  can you confirm that we're done with this? Per previous conversations (I think last Friday) I believe we're keeping the header minimal, and we're fast-approaching the point where it's going to be rather disruptive to add one later.

**Comment by clapierre** [comment]
Yes I think we can say we won't have a header and anything like Additional information, contact us, about etc. will be handled in the footer and keep a clean design up top.
