### ISSUE TITLE
User can search for a resources

### ISSUE THREAD

**Issue by benetechMatt** [benetech/ImageShare#4]
From the home page users can search for specific types of resources by entering text and have the option of narrowing the search criterial by choosing specific subject area, Resource Type, and / or  accessibility accommodation.

One the homepage there is the search input and a search button.  Taxonomy multi-select boxes below it:
Subject, Resource Type, Accessibility Accommodation. 

After clicking search users are brought to the search results page.

------
Search Criteria
Initially Search will use only resource_sTitle and resource_sTags.
We may expand this to also include resource_sDescription if we find we are not getting the desired results.
Search will initially be limited to "Whole Words only" so we don't get "h**ear**t" when you search for "**ear**".

Ideally searching for "ears" will find "ear" or searching for "ear" will find "ears". However, if this is too difficult to do we can split this to a new issue.

**Comment by sinabahram** [comment]
Closing because now handled in #34 and #35

**Comment by clapierre** [comment]
Closing because now handled in #34 and #35
