### ISSUE TITLE
Bulk Import of Resources

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#41]
The site should support importing resources from a CSV file, a schema for this file needs to be agreed to by the Team.
Once this is agreed upon Benetech will provide a sample file for testing along with the resources for development and testing.

**Comment by sinabahram** [comment]
@jkva   I think this is done but it is still open and there is no commit linked against it. Can you please link a commit against this and close if you agree? If there are bulk import errors or anything like that, we can always open a specific issue.

**Comment by jkva** [comment]
Implemented via 1735d04cd647e41b7008c4fcea7f2d49f48f75c5
