### ISSUE TITLE
Create custom theme for site

### ISSUE THREAD

**Issue by sinabahram** [benetech/ImageShare#42]
A custom child theme may be necessary here if we start with a barebones theme like Underscores or something similar. Genesis is the only framework that comes to mind as something that would be helpful. Most others are not good about html5 nor accessibility.

**Comment by sinabahram** [comment]
@jkva   I think this is done but it is still open and there is no commit linked against it. Can you please link a commit against this and close if you agree? The issue is only for creating it, not completing it, so I'd like to get this issue closed and linked against a commit since the custom theme has been created already.

**Comment by jkva** [comment]
Implemented via d9e01650469f42398a6445a4bdf62d62c8acf722
