### ISSUE TITLE
Header: Missing Search Label

### ISSUE THREAD

**Issue by jscholes** [benetech/ImageShare#43]
The search input (`id="search-form-1"`) has no explicit visible label.  A visual label is required, provided via a standard `<label>` element.

![Search input with the value "fdsa", but no visual label](https://user-images.githubusercontent.com/6454755/79773749-7635ed00-82f7-11ea-86d0-ab2866a0abc9.png)

**Comment by clapierre** [comment]
Unable to delete issues: We will close this as invalid and won't fix.
