### ISSUE TITLE
Header: Missing Search Submit Button

### ISSUE THREAD

**Issue by jscholes** [benetech/ImageShare#44]
The search button (`class="search-submit"`) is only displayed when it receives focus which drastically reduces its discoverability.  Users should be directly exposed to all of the functionality on offer, rather than needing to seek it out for themselves.  Indeed, many users will be unable to locate controls which are hidden by default without a pointer to their existence.

["SEARCH" button with dotted focus outline right aligned within search input](https://user-images.githubusercontent.com/6454755/79774797-e85b0180-82f8-11ea-958e-a14345056674.png)

#### Suggested Solution

The button should be persistently displayed to all users, regardless of state.  In addition, we'd suggest that:

* the button's text should use title case ("Search") rather than the text being rendered in all caps; and
* the button should fill the full height of the input, creating a larger target size for those with finer motor movement difficulty.

![Screenshot of the search button stretched to fill the full height of the input](https://user-images.githubusercontent.com/6454755/79775309-a8e0e500-82f9-11ea-8f59-3150318999a1.png)

##### CSS Styling

```
/* PAC: remove the following styles */
.search-modal .search-submit {
  position: absolute;
  right: -9999rem;
  top: 50%;
  transform: translateY(-50%);
}

.search-submit {
  margin: 0 0 0.8rem 0.8rem;
}
```

**Comment by clapierre** [comment]
Unable to delete issues: We will close this as invalid and won't fix.
