### ISSUE TITLE
Header: Non-Standard Skip Link Text

### ISSUE THREAD

**Issue by jscholes** [benetech/ImageShare#45]
The `<a>` with `class="skip-link screen-reader-text"` has the text, “Skip to the content”,, which is not standard messaging for this type of link.  A more recognizable string would be, "Skip to Main Content".

![Screenshot of the "Skip to the content" link](https://user-images.githubusercontent.com/6454755/79777385-c95e6e80-82fc-11ea-9f4e-30ea478a33c7.png)

**Comment by clapierre** [comment]
Unable to delete issues: We will close this as invalid and won't fix.
