### ISSUE TITLE
Footer: Missing Border Around Search Button in Windows High Contrast Mode

### ISSUE THREAD

**Issue by jscholes** [benetech/ImageShare#46]
The search button (`class="search-submit"` within the `<aside>` with `class="footer-widgets-outer-wrapper"`) displays no border in the Windows High Contrast mode.  Note that this problem also applies to the "reply" and "post comment" controls elsewhere on the site.

![Screenshot of the search input with a value of "fdsa", displayed in the Windows High Contrast Mode with no border](https://user-images.githubusercontent.com/6454755/79778507-6ff73f00-82fe-11ea-9b5f-e23a7d4b7141.png)

#### Suggested Solution

Add a border around the button which matches the background color.

![Screenshot of the same search input, again with the Windows High Contrast Mode enabled, but this time showing a border for both the input and the right-aligned search button](https://user-images.githubusercontent.com/6454755/79778739-dbd9a780-82fe-11ea-8a07-5ca48f60019f.png)

##### CSS Styling

```
button:not(.toggle),
.button,
.faux-button,
.wp-block-button__link,
.wp-block-file .wp-block-file__button,
input[type="button"],
input[type="reset"],
input[type="submit"],
.bg-accent,
.bg-accent-hover:hover,
.bg-accent-hover:focus,
:root .has-accent-background-color,
.comment-reply-link {
  background-color: #cd2653;
  border: 1px solid #cd2653;
}
```

**Comment by clapierre** [comment]
Unable to delete issues: We will close this as invalid and won't fix.
