### ISSUE TITLE
Design considerations

### ISSUE THREAD

**Issue by jkva** [benetech/ImageShare#47]
# Imageshare development

The current proposal is to split the WordPress development side into two parts: Plugin and Theme.

## Imageshare Plugin

Implements:

* Resource, as _WP\_Post_  (#38)
* Resource_file, as _WP\_Post_
* Collection, as _WP\_Post_ (#36)
* [Taxonomies], as _Taxonomy_ (#33)

As well as the specific Imageshare page controllers.

The goal is to use WP itself as much as possible. The one-to-many relation between `Resource->Resource_file` and `Collection->Resource` is achieved by using WP's `post_meta` facility.

The custom fields needed (Source, Contributor etc.) are also stored as`post_meta`.

One potential drawback of this is the requirement for full-text search; while InnoDB supports full-text search, WP does not use FT indices anywhere. Potentially this could be resolved by a separate search table (Resource id, title, description, (tags?)) which is used for FT search. This could be realtime or via a cronjob, depending on needs. (#34)

These design considerations are made under the assumption that Imageshare is high-read, low-write. Achieving relationships via `post_meta` is suboptimal, yet in a high-read, low-write environment this can be offset via cache optimisation.

## Imageshare Theme (#42)

Initially based on `_s` for barebones development. Templates etc. are written using Twig/Timber. 

## WordPress Plugins (#32)

* Advanced custom fields, for administration, managing resources, resource files and collections.
* Timber, for Twig templating
* Smackcoder's CVS import plugin (paid)
* (Potentially) Cache Enabler for resource page and/or search result caching. TBD.

**Comment by sinabahram** [comment]
I agree with all of this. I love Timber/Twig. That’s a nice way of avoiding some of the PhP hell of WP themes.

 

I updated the Search issue, #34, with some search plugin suggestions.

**Comment by jkva** [comment]
> (Potentially) Cache Enabler for resource page and/or search result caching. TBD.

Excluding, as per WP_Engine's list of excluded plugins.

**Comment by sinabahram** [comment]
I think this issue has served its purpose. Lots of these either have their own issues or are done.
