### ISSUE TITLE
Resource preview image as BLOB?

### ISSUE THREAD

**Issue by jkva** [benetech/ImageShare#48]
Why is the preview image stored as BLOB in the proposed schema? Could this be a post attachment or the default post thumbnail? Can these be links to images on a CDN, managed in WP's media library?

**Comment by clapierre** [comment]
Yes the preview Image as well as any resource file can be stored in the WP's media Library so links to that is fine.  Actually links to the images may be preferred if an external resource we don't own may have copyright issues with us storing even a  thumbnail copy of it, so we may have to link to an external preview image.  I really hope that isn't the case and we can have all preview images internal.  Or if linking to an external site for thumbnails is a problem we would just link to a default internal image for all resources from that external repository.

**Comment by jkva** [comment]
Closed as discussed and resolved.
