### ISSUE TITLE
Are collection contributors represented by CMS users?

### ISSUE THREAD

**Issue by jkva** [benetech/ImageShare#49]
Since a collection has a `collection_sContributor` field in the proposed schema, will this be the ID of the user whom created the collection?

**Comment by clapierre** [comment]
I don't think a Collection's contributor will be a CMS user, but this potentially could be in the future.  Benetech initially will be curating these collections for specific topics in middle school and high school science . We could also as we bring in partner schools add collections for their specific school, or organization that have collections already set up.  

This was just considered a field to acknowledge who's collection this is.  If you think it's best to do this via a CMS user now,  we could always add a user for this purpose, but for now this could be as simple as a text string.  I would assume if we initially went with a text field, we could in the future change this to be a CMS user with a little effort.  Thoughts welcome.

**Comment by jkva** [comment]
@clapierre given your description an arbitrary text field makes more sense. If indeed it becomes linked to a CMS user in the future, this can be a separate migration.

**Comment by sinabahram** [comment]
+1 to text field instead of a linked user.

**Comment by johnhbenetech** [comment]
Just chiming in here (feel free to ignore) - @clapierre  should we make this a 1 to many relationship from the get go? The contributor info can still be free text. Don't want to overcomplicate things unnecessarily, just wanted to bring this up if you think their may be multiple attributions on a single resource - or in the futre multiple "owners" of a resource.

Always something we can migrate later :)

**Comment by clapierre** [comment]
@johnhbenetech, This was specifically concerning the Collection's Contributor, who curated the collection, ie. "Mr. Jone's 6th grade Science" or "Peterson Highscool's Biology" which may have links to a DCMP video, some APH Tactile etc.  but the person who made the collection is one person.  I don't think there will be multiple people collaborating on a single collection, but maybe there could be.

I hadn't thought of a single resource or collection may have multiple owners, I guess if its a free form text field and we comma separate multiple owners/creators we can always separate them out at a future time if required.

**Comment by sinabahram** [comment]
+1 to not overcomplicating this. a ‘,’ between names is sufficient for now.

**Comment by sinabahram** [comment]
I believe this has been answered. @jkva  please reopen if the text field for contributor has not been added to the Collections post type. Closing for now.
