### ISSUE TITLE
User can create a collection of resources

### ISSUE THREAD

**Issue by benetechMatt** [benetech/ImageShare#5]
Collections allow users to organize resources around a topic they choose.

Each resource has a "add to collection" button. Clicking the button the first time will ask users to create a collection and give it a name.  After creating the collection, the resource is automatically added to it and the collection shows up in the drop down.

If users already have a collection that they want to add the resource to they will click on the collection and then "add" button.

Users can create additional collections

**Comment by clapierre** [comment]
Closing all non-MVP issues
