### ISSUE TITLE
Use CSS Borders When Background Colors Define Section or Content Boundaries

### ISSUE THREAD

**Issue by jscholes** [benetech/ImageShare#53]
Apply a CSS border matching the background color used to define a section.  For example, the search module on the home page has a gray (`#F2F2F2`) background, so applying a declaration of `border-top: 1px solid #F2F2F2` will ensure that the section's boundaries are shown in high contrast modes.

**Comment by sinabahram** [comment]
Can @jkva  or @vincent-young-1701  please confirm this is now handled in new designs/implementation and close if so?

**Comment by vincent-young-1701** [comment]
I've taken care of it it.  Closing.
