### ISSUE TITLE
Search Results: Misplaced “Advanced Search” Button

### ISSUE THREAD

**Issue by jscholes** [benetech/ImageShare#58]
Similar to #55, an “Advanced Search” button (relating to the "Refine Results" input) is positioned after the submit button for the form rather than before it.

![Screenshot of the search input, with “Advanced Search” button appearing after submit.](https://user-images.githubusercontent.com/6454755/80003048-115ccd00-8486-11ea-8265-82bb92a73e82.png)

**Comment by clapierre** [comment]
I assume what we do now for #55 will be similar here and this can be done the same way.

**Comment by sinabahram** [comment]
This is resolved in new designs/implementation.
