### ISSUE TITLE
Search Results: Problematic "Read More" Links

### ISSUE THREAD

**Issue by jscholes** [benetech/ImageShare#61]
"Read More" links are used as a means of displaying content, as opposed to it being visible by default.  This can reduce discoverability, in result in several controls with the same text/accessible name.

Consider displaying content by default where it makes sense, and ensuring that context is provided for these types of links so that they can easily be distinguished from one another.

![Screenshot of the blue, underlined “Read More” link, appearing at the end of the lorem ipsum text.](https://user-images.githubusercontent.com/6454755/80006058-fc823880-8489-11ea-9a96-25a83344ca08.png)

**Comment by clapierre** [comment]
I am fine if we just have the entire description appear here no matter how long it is.  If we need to limit it we can cross that bridge later.  I don't think we will have descriptions that would go on for pages anyways.

**Comment by sinabahram** [comment]
These concerns have all been addressed in new designs.
