### ISSUE TITLE
Initial Design Review

### ISSUE THREAD

**Issue by vincent-young-1701** [benetech/ImageShare#66]
@clapierre  I’ve mocked up something for the homepage.  Nothing groundbreaking here but just a quick refresh that includes the updated search module.

I can mock up the other pages quickly once I get feedback here or if just you want to stick to the original design + updated form.  Either way let me know.  Thanks.

![image](https://user-images.githubusercontent.com/25315048/80246006-924fcc00-8620-11ea-984d-f1e7c090c193.jpeg)

**Comment by vincent-young-1701** [comment]
@clapierre if you can mainly focus on the layout, things like colors of the collections and font sizes could always be determined later.  Thanks!

**Comment by clapierre** [comment]
Sure thing, just waiting to hear back from my UI/UX peeps.  I will ping them again!

**Comment by clapierre** [comment]
@vincent-young-1701 Here is what one of our UI/UX designers has said:

> I like the colored bars below the images and I like the black footer instead of white.  The contrast is good.  I also think putting the Search back at the top is good if the Browse Collections region is visible above the fold on a standard laptop resolution.  Rather than the Search Library button taking up a whole line horizontally, I would put it to the right of the Search bar.  Bar doesn’t need to be so long and that would give more room for the collections.   If you want, I can update the mockup to show this.

I will mention to her that we moved the Search button down after the advance options for accessibility concerns. So I think we can ignore that comment.

**Comment by vincent-young-1701** [comment]
Understand where she is coming from... I'm just going to throw this out there, if you guys do not want to go down this route, just ignore, but I think it makes sense for me to put it forward as an option.  If possible, having the search on the right makes more sense to me from a visual UI perspective.  The interaction flows better from left to right and the content below gets brought up which is why you often see that layout.  The issue we ran into was with the advanced search and the visual order not matching the tab order; well, I've mocked something up and think it works well.  Some added CSS and one extra line of JS (JS is needed anyway to open/close).  I've attached an example as well as how the design would look.  Let me know what you guys think and please, feel free to disregard.  I had to zip the example index.html file in order to upload.

![Desktop-idea](https://user-images.githubusercontent.com/25315048/80414836-7e0d0880-8886-11ea-816f-b961a9f48b0a.png)

[index.html.zip](https://github.com/benetech/Imageshare/files/4541750/index.html.zip)

**Comment by clapierre** [comment]
Hi Vincent, this looks very good I think, I like the responsive design approach so that when you narrow the screen size the Advance Options and Search button move down below the Help String.  
I think this is a good compromise and gets to the issues Deanna was thinking with the very long search field input being the entire width which is not really necessary and this will save a couple lines which is a good thing.

**Comment by clapierre** [comment]
Just showed the rest of the team and everyone loves the landing page and responsive design of the index.html file.  So you are good to go on the other designs this one is in the bag.  
Thanks

**Comment by vincent-young-1701** [comment]
Great.  There won't be much change with those pages, but let me create those quickly so we can see how they look.

**Comment by vincent-young-1701** [comment]
@clapierre linked are the updated designs.  As you can see, didn’t change too much.  On the search results using the same search module as the home, and seems just labelling would need to change.  I put in a  header background color which also carries over to the detail page so there’s more consistency.  I took out the red on the detail page and just stuck to the blue theme.  The left column there seemed out of place, so all the content is now left aligned and the “back to results link” is now at the top and the “report issue” button is in the top right sitting in a column.  Let me know if this works out better and let’s comment in those individual tickets.

@clapierre 

I’ve got the updo designs in two separate tickets so we can keep better track.

https://github.com/benetech/Imageshare/issues/67

https://github.com/benetech/Imageshare/issues/68
