### ISSUE TITLE
Detail Page Design Review

### ISSUE THREAD

**Issue by vincent-young-1701** [benetech/ImageShare#68]
![image](https://user-images.githubusercontent.com/25315048/80505701-879b7c80-8929-11ea-8cd8-7773c6ecaf06.png)

Here on the detail page is the same consistent header with blue background and ImageShare logo left aligned.  I stuck to the blue theme text and replaced red “Description” heading and red accents in tab bar. The left column preciously seemed out of place, so all the main content is left aligned and the “back to results link” is now at the top directly before main heading and the “report issue” button is in the top right sitting in a column. Let me know if this works out better.

**Comment by clapierre** [comment]
I am good with the color scheme, much better than the Red text.
I also agree the left sidebar seemed out of place since we didn't have it everywhere.
I would not expect there to be many issues so having that "Report Issue" at the top and so prominent doesn't seem appropriate.  I would think we move that to the bottom of the page after "download selected files" button.

**Comment by vincent-young-1701** [comment]
Got it.  Good context.  Here is the Report Issue button removed and appearing at the bottom right aligned.  I've made it into an underlined link.  I think this is going to be a link, correct?  Is it an e-mail link?

![Detail Page Desktop](https://user-images.githubusercontent.com/25315048/80522451-7494a680-8941-11ea-9146-bf315739fe1f.png)

**Comment by clapierre** [comment]
Yeah I think for now it will be an email link we will figure out later.  We can always improve that in the future to be a form but for now this is fine.
I like that.  This looks good now!

**Comment by vincent-young-1701** [comment]
How does this look?  Keeping it simple is always my initial approach.  I think if after implementation, we feel both at the top and bottom is needed along with pagination, we can add in.  Thoughts? 
![Search Results Desktop](https://user-images.githubusercontent.com/25315048/80526282-5d58b780-8947-11ea-809e-1bd5da208b5d.png)

**Comment by vincent-young-1701** [comment]
Great!
