### ISSUE TITLE
WPEngine Support Needed: Coyote Plugin redirection issue

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#69]
Would it be possible to please file this ticket with WPEngine support,
unless if you know of a solution we have overlooked. This is a bit of a
blocker.

Major thanks to Job for deep-diving on the below!

**ticket**

TLDR:
There is either a problem with our plugin, WPEngine's rewrite rules or with
WPEngine's way of executing the following URL:
https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fchsdmdev.wpengine.com%2fwp-content%2fplugins%2fcoyote%2fphp%2fpublic%2ftools.php&c=E,1,ujMxyMM3AsyVC_lAJZeyq0MevHDdL9dH9-19jx7MGKse7ONfVHTllmkokxlEmw0RBuQgbs43L5u6ad9SpqAeS8cqYDAGlAkvpbABDhEVD1hqaQ,,&typo=1

background:
We are building a custom WordPress plugin, "coyote". This plugin contains a
custom php file, which gets POST'ed to via a form submit on the plugin
options page, which, after having finished its work, redirects back to the
plugin options page.

The Problem:
While this works as expected on a local development environment, instead
redirecting back to the plugin options page on the WPEngine instance results
in an Internal Server Error. The WPEngine error log reads:

[Wed Apr 29 06:36:26.584601 2020] [core:error] [pid 26808] [client
80.101.162.148:56254] AH00124: Request exceeded the limit of 10 internal
redirects due to probable configuration error. Use 'LimitInternalRecursion'
to increase the limit if necessary. Use 'LogLevel debug' to get a
backtrace., referer:
https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fchsdmdev.wpengine.com%2fwp-admin%2foptions-general.php%3fpage%3dcoyote_field&c=E,1,KVqTqR5RI_etlq5wAcmK10HQwzhKB5f6b1gWOZurTAy0NN7Bt1LEeupuxWPiUqw1EXOsKZWZH3yOGO7KMGfGiyokhkGfNFjJOA8z8GYfM8Bwzw,,&typo=1
s

Possible explanation:
The redirection is achieved in php code via `wp_redirect(wp_get_referer())`.
The function `wp_get_referer()` uses the following variables: 

* `$_SERVER['REQUEST_URI']` 

* `$_REQUEST['_wp_http_referer']`  via `wp_get_raw_referer()` (set via
hidden form field to `<input type="hidden" name="_wp_http_referer"
value="/wp-admin/options-general.php?page=coyote_fields">` as is WordPress
practice)

* `$_SERVER['HTTP_REFERER']` via via `wp_get_raw_referer()`

When logging these on a local development environment, they read:

```
(
   [$_SERVER['REQUEST_URI']] =>
/wp-content/plugins/coyote/php/public/tools.php
   [$_REQUEST['_wp_http_referer']] =>
/wp-admin/options-general.php?page=coyote_fields
   [$_SERVER['HTTP_REFERER']] =>
https://local-development/wp-admin/options-general.php?page=coyote_fields
)
```

According to WordPress' runtime logic, in this case the value of
`$_REQUEST['_wp_http_referer']` would be used, since it's non-empty and not
equal to `$_SERVER['REQUEST_URI']`. If it were empty,
`$_SERVER['HTTP_REFERER']` would be used, which should then still redirect
to the right location.

Our suspicion is that one of these variables causes a problem with a rewrite
rule on WPEngine's side. That's at least what the error suggests. This still
leaves us with the question why the similar post-redirect-get flow that
WordPress' own options pages use works without a problem, since I'm using
the same mechanism.

Additional Notes:
it's not entirely obvious that the redirection after the processing is the
problem. When we manually request
`https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fchsdmdev.wpengine.com%2fwp-content%2fplugins%2fcoyote%2fphp%2fpublic%2ftools.ph&c=E,1,p67IR5wTNJNYxmlXEXt1UzSguPvNr4uP7m0znk7GsOGGUuvxhU3lzXnl4SzEHRXF2UUCpZOijUxE9zl16ntlZXUe6QnhOn8dk676NmO2TyRlMSvKCQ,,&typo=1
p` we _also_ get the Internal Server Error. So it seems the actual code is
never even run since the uri itself causes a redirection loop.

**end ticket**

**Comment by sinabahram** [comment]
This was my mistake. Wrong project. Closing this ticket.
