### ISSUE TITLE
Purchase and add WordPress CSV plugin to Staging & Dev 

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#70]
Smackcoder's CVS import plugin (paid) - https://wordpress.org/plugins/wp-ultimate-csv-importer/

The plugin is $150 - do you think we need to run it by Lisa? Seems like not a big deal. I have a company card so that's not an issue

Charles LaPierre:spiral_calendar_pad:  9:22 AM
No lets just do it we need it.

**Comment by sinabahram** [comment]
I would like to have an internal plugins convo with @jkva before we finalize our list of plugins and then you can buy whichever are needed.

 

We’ll try to have that before end of week.

**Comment by diagram-codesprint** [comment]
After discussing this with Sina, we may not need a CVS plugin, and instead use a JSON file to import in all resources. 
Once that is decided we can close this ticket and create separate tickets on JSON schema and CVS to JSON scripts

**Comment by clapierre** [comment]
After discussing this with Sina, we may not need a CVS plugin, and instead use a JSON file to import in all resources. 
Once that is decided we can close this ticket and create separate tickets on JSON schema and CVS to JSON scripts

**Comment by sinabahram** [comment]
@jkva, @jscholes, and I  discussed this further. We are good to close this. Let’s replace with a ticket about JSON manifests where either James or Job can fill in initial details into that ticket.

**Comment by clapierre** [comment]
I agree with this new plan and switching to a JSON approach will make importing easier and help when we add the addition of an API to interact with Imageshare since the API will be JSON by default.
I will create the new JSON ticket
