### ISSUE TITLE
Report Issue Link Position On Detail Page Incorrect

### ISSUE THREAD

**Issue by vincent-young-1701** [benetech/ImageShare#73]
The report issue link on the detail page needs to be position at the top of the page, closer to the return to search results link.  Currently, It could be missed by users placed  after the download selected files submit button.

**Comment by clapierre** [comment]
Can we get a quick mock up for this.  I am thinking an unobtrusive small text link "report issue".

**Comment by vincent-young-1701** [comment]
I can do that as soon as I get my laptop back from Apple.  Should be tomorrow.

**Comment by vincent-young-1701** [comment]
@clapierre what do you think of the report issue link placement?  It's floated to the right of the back to search results page.  Since we shrunk the content width I think it makes sense for it to be in the far right empty column to reconcile that.
![report-issue](https://user-images.githubusercontent.com/25315048/81595948-1f608800-9378-11ea-9dd2-b1c6725bb814.jpg)

**Comment by clapierre** [comment]
perfect, thanks!

**Comment by sinabahram** [comment]
Closing this because other issues exist for UI/UX now.
