### ISSUE TITLE
Optional Production Notes and Video Length 

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#75]
In looking over the resources while creating a master CSV file for use on importing resources into Imageshare it was clear that we were missing a couple fields that will be needed for Imageshare to be useful for certain types of resources.

For Resources that are to be printed out either by a tactile or 3D printer there may need to be a "Production Notes" section that would describe the type of paper and size to be used.

Eg:  For a Tactile image the "Production Notes" would look like.

> **Production Notes**: Intended for 11×11.5 inch sized swell paper.

And for a 3D model the production notes may look like:

> **Production Notes**: All the 4 files in the zip folder can be printed at once on a 3d printer with at least 10cm x 10cm x 10cm printing area. Make sure that the height of each block is 2.2cm when it is aligned in the printing software so that the braille side is facing up. If not, calculate the relative percentage and scale it down to 2.2cm height. Best printed in ABS. Try to scrape off the support material while fresh off the printer. Try not to touch the braille dots till it has cooled off completely.

For audio & videos we would have a "Length" which would be a text field and contain something like

> **Length**: 2 minutes
or
> **Length**: 1 hour

This information would be presented to end users on the Details Page, along with other information such as the License, Source, Tags, etc.

**Comment by sinabahram** [comment]
Does this belong as a field of file or resource? What if a resource has both a 3-D model and an image and an audio file, which is not at all unusual, right e.g. here’s a photo of the thing. Here’s how to 3-D print the thing, and here’s an audio description of the thing.

 

Then things like length don’t have meaning, except on the audio file.

**Comment by clapierre** [comment]
Right so maybe it doesn't belong in the Details tab unless the Details will change base on the item selected.  Or we move that information into the file information.  Same like simplified and extended description potentially as well.

**Comment by sinabahram** [comment]
Quick thing, to avoid confusion, let’s please not discuss UI issues when we are discussing the data model. They have absolutely nothing to do with one another at this stage.

 

So, let’s just concentrate on Resource VS File. Not anything having to do with details or tabs or anything UI/UX related.

 

My question is as follows.

 

Do these fields belong on Resource or on File?

**Comment by clapierre** [comment]
Length and Production Notes would belong on the File level.

**Comment by sinabahram** [comment]
Ok, sounds good.

 

@jkva please add these two fields to File in ACF.

**Comment by sinabahram** [comment]
These concerns have all been addressed in the import file and related script.
