### ISSUE TITLE
Collections Tab Design Review

### ISSUE THREAD

**Issue by vincent-young-1701** [benetech/ImageShare#77]
@clapierre @sinabahram I've got the collections displayed vertically in a scrolling container with collection name as a heading link and below that the authors name and then creation date.  Resources heading follows and then resources are laid out horizontally with image on top and description below, same as the current result images on the page above.  Might make sense to layout things vertically if no resource images will not play well with the horizontal layout.  Let me know what you think.  This was the quickest/easiest solution I came up with.

![Collections Detail Page Desktop](https://user-images.githubusercontent.com/25315048/82031094-32ac7580-964e-11ea-8c8d-fcecc0b646f4.png)

**Comment by clapierre** [comment]
Hi @vincent-young-1701 That is not what I was envisioning actually.

We don't need to include all the resources for each collection here.
Just a Table containing the Collection Image, Collection Name, Author, and Date
The Image can be described by the Collection name, or made purely decorative whatever we feel is best.
Where the Collection Name is a link to that collection's resources. (which is the same page we already created when you click on a collection from the main landing page)

**Comment by vincent-young-1701** [comment]
Something like the following where each is separated by a horizontal rule with collection title, new line, author, new line, date, new line, image?

![Detail Page Desktop - Collections ](https://user-images.githubusercontent.com/25315048/82089531-a2e7e500-96a8-11ea-9def-a30927ff47a2.png)

**Comment by vincent-young-1701** [comment]
Or were you looking more for a traditional table structure?  I wanted to move away from that as the design would be a bit table heavy.

**Comment by vincent-young-1701** [comment]
@clapierre Another option if all the images will be the same size, is to right align the text to them.

![Detail Page Desktop - Collections 2](https://user-images.githubusercontent.com/25315048/82090501-8ea4e780-96aa-11ea-9c6b-2ad48ad82cb9.png)

**Comment by clapierre** [comment]
Yeah I like the last approach.
Thanks

**Comment by vincent-young-1701** [comment]
Great.  Closing.
