### ISSUE TITLE
AWS S3 bucket needed for Imageshare

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#78]
Since we are now blocking on this we will need to get an S3 bucket to store all the Imageshare resources up and connected quickly.

Only the Featured Image will also get added to the WP database for performance related requirements.

This will be a temporary location until we can get the Systems team to set up the new Labs Child AWS account that we can manage our own S3 buckets, at which point we will migrate the data from this S3 bucket over to the new Labs S3 bucket

**Comment by sinabahram** [comment]
Just two quick things on this:

 

1: The featured image is also S3. This is why we included the featured alt in the spreadsheet, so as to allow the image to be in S3 and for the import into WP to know what alt text to assign the featured image of a resource.

 

2: I’m noting here that once the transition between buckets happens, someone will need to update the S3 URLs for the files in the system. Doing or scripting that isn’t in scope for us, so just wanting to flag it now so resources can be assigned.

**Comment by clapierre** [comment]
@sinabahram Yes on both accounts.  I will be uploading the files to S3 and then will proceed to update the excel spreadsheet / Tabbed separated text file, and hopefully will be able to run your script to generate the updated JSON file manifest :)

**Comment by clapierre** [comment]
John has finished uploading all our current initial resources to a temp S3 bucket.
We should have the final endpoint in the next week or so.  Will keep this open until we have the final S3 bucket in place.

**Comment by sinabahram** [comment]
I'm super-confused by this message.

If the final endpoint is available in a week, a temporary bucket is completely not needed and only adds a ton of extra work.

When last we talked, it was stated that it would take "months" not "a week" to get an S3 bucket.

Has this changed? If so, then great.

We should not do anything with this until the final endpoint is available if it is only a week from now.

Again, once imports are made into WP, re-importing on top of them becomes far more extra work, so let's be intentional about how we do this.

**Comment by clapierre** [comment]
@sinabahram We don't know when Systems will get to this, all we know its in their queue and right now it is ranked 121 of items they need to work on over the next 3 weeks.  They said it may get worked on but we have no idea when.  Also just talking with @johnhbenetech and it looks like we probably won't have any changes to the URI's.

> also i read a bit more on how aws deals with domains, i believe we will be able to migrate the s3 to the child account without having to update anything. essentially i rename/delete the current bucket and then within 24 hours that domain gets put back into availability and then i would just steal it for the child account.

So the URI to our S3 bucket theoretically won't change.

**Comment by sinabahram** [comment]
Charles, that’s excellent news RE the mapping. Super-nice!

**Comment by sinabahram** [comment]
Are we good to close out this issue? @johnhbenetech, I'll let you do so.

**Comment by clapierre** [comment]
@sinabahram should we keep this until we have the final S3 bucket, which we should get set up this week I hope as Systems has finished I believe setting up our Lab's AWS Child account so we can create our final Imageshare S3 bucket I believe.  @johnhbenetech you agree?

**Comment by sinabahram** [comment]
This is now done according to Slack. Closing this.
