### ISSUE TITLE
What determines which collections get displayed on the landing page?

### ISSUE THREAD

**Issue by jkva** [benetech/ImageShare#79]
This could be something like a 'highlighted' flag, or a combination of factors such as collection size or recent modification.

**Comment by sinabahram** [comment]
Let’s please reduce complexity here. I recommend a Boolean on the collection e.g. highlighted or featured, whatever term is appropriate.

**Comment by clapierre** [comment]
Agreed

**Comment by sinabahram** [comment]
This is resolved
