### ISSUE TITLE
Where should Resource Collection artwork be stored?

### ISSUE THREAD

**Issue by jkva** [benetech/ImageShare#80]
They can be either stored as WordPress media files, or be arbitrary URLs. What has preference? Currently I store them as WordPress media files for easy preview when editing Resource Collections.

**Comment by sinabahram** [comment]
I think Wp  is appropriate because they are purely an Imageshare concept, whereas the other things like resources and especially files are external concepts so it makes sense to store them in S3.

 

Let’s go with that for now.

**Comment by clapierre** [comment]
I agree they would be stored in WP.
Thanks

**Comment by sinabahram** [comment]
This is resolved.
