### ISSUE TITLE
Resource Page UI/UX Design

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#81]
We are moving away from a Tabbed layout design on the Resource Results page and instead streamlining it to have only one main Table with 3 columns to simplify the design to make it easier to manage on mobile.

The new layout will have

Resource Name
Resource Description
Resource Subject Area
Resource Tags
Download All Button
3 column Table (Image, Name, file description / Details)
In each row's file description there will be a "Summary/Details" to expand the files details
which expand in that same row showing the following file details.
Type: ***
Format: ***
Language: ***
Accessibility ***
License: ***
Length: *** (Only shows if we have this metadata for audio/video files)
------
[repeats for each file in the resource under the description of the file]
After the table of files there is a 
Collections (#) (Summary/Details)
which will expand/collapse to show all collections this resource belongs to.

Here is a mock-up of this
You can click on either the "printed hearts" or  "kidneys video" details and collections to show/hide the data.
https://96i7ux.axshare.com/#id=bavpgp&p=image_detail_page

**Comment by clapierre** [comment]
@sinabahram @jscholes @jkva 
Here is the latest UI design for the details page, let me know if you have any questions.

**Comment by sinabahram** [comment]
Hi, did this mean to say details page?

 

we haven’t discussed any changes on the results page.

 

I noticed a later post with the details page posted, so I’m a bit confused.

 

Also, hiding/showing collections is something I’m just hearing about for the first time right now, so I definitely don’t think that’s the way we should go, just to add a topic for our Friday call. if they need their own page, that’s one thing, but I think they should just be presented exactly like a search result, except the results are the collection’s contents e.g. the resources in that collection.

 

Hoping we can resolve all of this tomorrow 100% of the way, and it’s totally possible I’m just missing something, so apologies if so.

**Comment by clapierre** [comment]
@sinabahram this is exactly what we discussed earlier this week.
When I say "resource page" this is the final page the resource with all its files which make up this resource. with the table of 3 columns icon file name and file descriptions with the "button" or show/hide "details" ie. file details which expands vertically inside that row in the table showing the file details ie. language, accommodations. license" etc. just like we discussed.

We also discussed that at the end after the table of files making up this resource instead of having a tab for collections we discussed the idea of a button to text to show/ or hide the collections for this resource.  so this is exactly the design we discussed on Tuesday.

**Comment by sinabahram** [comment]
Yeah, exactly. That's good news. We have a naming problem, not a design problem, so let's resolve that. Let's refer to the homepage as the index page, then there is the "Search Results" page, and then there is the "Resource Details" page. That's why I asked if your comment meant to say the resource details page because there is no resources page. Now, I completely agree with it all, but before I was interpreting that stuff to apply to the Search Results page. Phew.

**Comment by clapierre** [comment]
Sure thats fine Index vs landing page, and I was already calling the Search results page, and now the Resource Details page is fine :)

**Comment by sinabahram** [comment]
Just flagging for @jkva  to implement this.

**Comment by sinabahram** [comment]
@jkva  you are also good to remove summary/details from overall collections portion of the page, as we discussed on the phone. It just adds noise, and not having it makes htis easier for folks.

**Comment by jkva** [comment]
@clapierre It says in the layout description:

> 3 column Table (Image, Name, file description / Details)

Yet resource files do not have an image (unless it's a type of image file) nor do they have a description or any details. At least not that I can tell in the current schema.

**Comment by sinabahram** [comment]
There are two options here:

 

1: Charles et al. provide generic images to be used for documents or other formats

 

2: we do not display thumbnails when the file is not an image

**Comment by jkva** [comment]
@sinabahram right, regarding option 1 - a set of fallback thumbnails, one for each file type, might be good here.

**Comment by clapierre** [comment]
Yes I will provide thumbnail images.

**Comment by jkva** [comment]
@clapierre what about resource file descriptions? Will those be added to the schema?

**Comment by sinabahram** [comment]
@jkva, I don’t understand this question.

**Comment by jkva** [comment]
The current master schema (https://github.com/benetech/Imageshare-utils/blob/master/Data%20Files/Imageshare-Master-utf8.json) contains no descriptions for resource files. But the mockup seems to assume that's not the case. I'm trying to find out if I need to change the resource file data model to account for this.

**Comment by clapierre** [comment]
@sinabahram we have a 3 column table for the Details for each file in this resource,
Icon, name and description.  Yet in our schema / excel spreadsheet we don't have a place to put the file description, we only have the resource description field.

I think we need to add a field description to the spreadsheet.
Otherwise we will just have "details / summary showing in this column.  But we may need to have extra file description to explain what this file is if it looks identical to some other file in this resource.

**Comment by clapierre** [comment]
Uploaded changed to the taxonomy and excel spreadsheet / utf16 txt file adding the new column file_description

**Comment by jkva** [comment]
As per #116 this page now uses flexible lists to render its content. Implemented via 3b3c3b8b8d616da1b3563a1450608a5a10365480.
