### ISSUE TITLE
Remove skip-to-content as superfluous

### ISSUE THREAD

**Issue by jkva** [benetech/ImageShare#83]
Instead, "Skip to search".

**Comment by sinabahram** [comment]
Important qualifier, on the index page.

I’m explicitly signing off on this. It’s just silly. We have one link before the content. Adding skip to content makes the site less, not more, accessible.

Now, @jscholes  can you weigh in on the skip to content link being on the search results or details page? I could see it being far more useful and in fact necessary there. Do you agree?

**Comment by clapierre** [comment]
YEs I agree lets remove the Skip to main Content from the index page.  Sorry I forgot this was an issue with my latest issue #102. I will re-evaluate #102 on subsequent pages once I can see them again :)

**Comment by jkva** [comment]
Removed skip link on index page via 850e17a593ca3a9179a315f34b219544f82a4589
