### ISSUE TITLE
User can download all or part of a resource

### ISSUE THREAD

**Issue by benetechMatt** [benetech/ImageShare#9]
Resources . have a "download" button. Clicking it opens up a new modal that lists the files available to download from the resource and additional options.

options:
- save as original files only
- save as webpage with accessibility data
- save .txt file with accessibility data and files

users click checkboxes next to files in the resource to select which ones they want to save.   They can also click "select all"

Anything beyond an individual file will download as a .zip file

**Comment by clapierre** [comment]
Closing all non-MVP issues
