### ISSUE TITLE
Need email address for 'report an issue' functionality

### ISSUE THREAD

**Issue by sinabahram** [benetech/ImageShare#91]
The report an issue link needs to be a mailto link. Assigning this to both @clapierre  to provide the address and to @jkva  to implement.

**Comment by jkva** [comment]
@clapierre any progress on this?

**Comment by clapierre** [comment]
Just pinged our IT department should have an email address for you shortly.

**Comment by clapierre** [comment]
@jkva Here you go: imageshare-issues@diagramcenter.org

**Comment by jkva** [comment]
Addressed via 9a6839ddb0701c90ffc215cd0d24e67ce2a8e0e1
