### ISSUE TITLE
Add checkbox to search within results

### ISSUE THREAD

**Issue by sinabahram** [benetech/ImageShare#92]
The search results page needs a way of refining results, but also to not make it difficult to just search for other resources/collections as well. To that end, let us do the following, @jkva.

On the search results page, add a checkbox after the edit field but before advanced search that says "perform search within results". Only when this checkbox is checked should the subsequent search be carried out against the previous search results.

Note, @jkva , this need not be complicated on the backend because we don't do anything complex here, etc. Simply add the previous search criteria to the current search criteria, carry out two searches on the backend, or whatever else makes this straight forward.

**Comment by jkva** [comment]
Implemented via 35f533fe09504e9fd135ba5505c6504d62be29bb
