### ISSUE TITLE
How to show both collections and resource results

### ISSUE THREAD

**Issue by sinabahram** [benetech/ImageShare#94]
The solution for this is very simple @jkva .

Just show collection results in same exact way as resources but as separate table before resources results. The only reason for not putting them in the same table is then we'd have to distinguish between which rows are a resource or a collection, and adding a column is not an option.

Just have note saying "no collections found" in area where table would go or "no resources found" where table would go, when there's no results.

**Comment by jkva** [comment]
Should collection results be a consequence of a search where no query terms are used? 
Say, if I search for resources with subject "Science", should the resultset contain collections which contain resources with that subject?

**Comment by clapierre** [comment]
@jkva thats a good question.
Should we have a main subject area for each collection?  That might make a lot more sense,
The other option would be to do a 2nd search for those resources within the collection that match that subject area, I would think having a subject for collections might be a better option.
Ugg but then what about accommodations and keywords.

Thoughts @sinabahram?

**Comment by sinabahram** [comment]
Full stop. Let’s just go with Job’s original suggestion. The answer, Job, is “yes”, from my side. If the collection is in that subject, then it shows up.

**Comment by jkva** [comment]
Works for me 👍

**Comment by clapierre** [comment]
So @sinabahram so how do we know if a Collection is within that subject?

**Comment by jkva** [comment]
@clapierre I track custom index metadata for a collection based on its members.

**Comment by clapierre** [comment]
Excellent!  what about Keywords and accommodations?

**Comment by sinabahram** [comment]
Yup, as Job said, a collection knows about it’s constituents, so this is determinable.

**Comment by jkva** [comment]
@clapierre regarding keywords and accommodations, I should be able to do so similarly.

**Comment by clapierre** [comment]
Excellent, I like this approach!  Thanks

**Comment by jkva** [comment]
Implemented via 3b2a4522e3150e0035c478529b0507ddc0d70afb
