### ISSUE TITLE
Subject hierarchy

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#97]
Hello all, just want to make sure everyone is in agreement with this
Below is our latest thinking for Subject classification.  Anything at the 3rd level will be put into keywords.  Let me know if this all makes sense or if anyone has any issues as my daughter is trying to organize the DCMV video spreadsheet to match our thinking for Subject and Keywords.
 (BTW the complete list we have so far is located in the Imageshare-utils/data files/Imageshare MVP Database Taxonomy.docx file, under H3 "[7] Subject  (Initially for MVP only Science)", which she will be updating as she goes.
Here are some of them with some examples of the keywords where we have them already defined.

Science (Main Subject)
  Earth Sciences (Our Subject)
     Geology (keyword)
     Agriculture (keyword)

  Life Sciences (Our Subject)
    Biology (keyword)
    Cells (keyword)

  Physical Sciences (Our Subject)
     Chemistry (keyword)
     Physics (keyword)

  Animal Sciences (Our Subject)
    Mammals (keyword)
    Zoology (keyword)

  Space Sciences (Our Subject)
    Aeronautics (keywords)
    Astronomy (keywords)

Math (Main Subject)
    Geometry (Our Subject)
    Algebra 1 (Our Subject)

Engineering (Main Subject)
    Agricultural Engineering (Our Subject)

Technology (Main Subject)
    Circuits (Our Subject)
    Computer Programming (Our Subject)

History (Main Subject)
    Holidays (Our Subject)

Linguistics (Main Subject)
   Sign Languages (Our Subject)

**Comment by sinabahram** [comment]
I have no issues with any of this, as it’s mainly content, but just to note that “circuits” can very much be a child of physics, for example, so be careful with that one.

**Comment by clapierre** [comment]
Understood, and closing this as we seem to be narrowing in on a final Taxonomy, which will continue to expand as we get more content.
