### ISSUE TITLE
Implement paged search results

### ISSUE THREAD

**Issue by jkva** [benetech/ImageShare#98]
Given the functionality of refining search (searching within search results, #92) it makes no sense to have paged results there unless there are loads and loads there. Can that be the case?

We're rendering result tables ordered by relevance. Should those be paged after say, 30 results, or should we display a message "please refine your search terms..." of some kind?

**Comment by sinabahram** [comment]
We still need pagination, yes. the control lets one pick e.g. 20, 50, or 100 per page, which I think is a good preset. Plus, this is necessary at any rate when doing browse operations e.g. searching for all science.

 

So, we definitely must have pagination.

**Comment by jkva** [comment]
Implemented via ddf29a1a8bf7062425d5015e1b3a718079c55304

**Comment by clapierre** [comment]
If I select show me 5 results per page and there are 13 results I only get 2 pages of results instead of 3 pages.

**Comment by jkva** [comment]
Good catch, thanks. Fixed in 6d72dd3b45a703ee4816e7623282de9ddf5c55a5
